import {queueMatch,spectateFriend} from './match-launch.js';
import {randomUUID} from 'node:crypto';
import {safeProfile,VERSION} from '../../src/data.js';
import {SocialStore,normalizeFriendCode} from './social-store.js';
const displayCode=c=>c.slice(0,5)+'-'+c.slice(5);
export const PARTY_LIMIT=4,RECONNECT_GRACE=30000,HEARTBEAT_TIMEOUT=45000,INVITE_TTL=60000;
// Durable identity, lobby membership and one-match admission are separate records.
export class PartyService{
 constructor(relay,{store=new SocialStore()}={}){this.relay=relay;this.store=store;this.users=new Map();this.parties=new Map();this.invites=new Map();this.tickets=new Map();this.timer=setInterval(()=>this.sweep(),5000);this.timer.unref?.();}
 connected(u){return !!u&&[...u.sessions.keys()].some(ws=>ws.readyState===1);}
 send(u,message){if(!u)return;const raw=JSON.stringify(message);if(message.type==='launch'){if(u.ws?.readyState===1)u.ws.send(raw);return;}for(const ws of u.sessions.keys())if(ws.readyState===1&&ws.bufferedAmount<65536)ws.send(raw);}
 create(u){const p={id:randomUUID(),leader:u.id,members:[u.id],privacy:'invite',selection:{mode:'royale',teamSize:1,teamFill:true,duoFill:true},state:'idle'};this.parties.set(p.id,p);u.party=p.id;return p;}
 snapshot(p){return {id:p.id,leader:p.leader,privacy:p.privacy,selection:p.selection,state:p.state,members:p.members.map(id=>{const u=this.users.get(id);return {id,profile:u.profile,ready:!!u.ready,inMatch:!!u.inMatch,connected:this.connected(u),presence:this.presence(id)};})};}
 sync(p){if(p){const party=this.snapshot(p);for(const id of p.members)this.send(this.users.get(id),{type:'party',party});}this.changed();}
 publishPublicMatch(match){for(const u of this.users.values())this.send(u,{type:'public-match',match});}
 changed(){if(this.changeTimer)return;this.changeTimer=setTimeout(()=>{this.changeTimer=null;for(const u of this.users.values())this.send(u,{type:'social-changed'});},100);this.changeTimer.unref?.();}
 matchLocation(u){if(!u?.inMatch)return null;const peer=this.relay.peers.get(u.matchPeer);if(!peer)return null;const room=this.relay.authority?.roomFor(peer),host=room?.hostPeer||this.relay.peers.get(`yolk-yard-v${VERSION}-${u.matchCode}`)||[peer,...peer.links.values()].find(p=>p.listing);if(!host?.listing||!['lobby','playing'].includes(host.listing.phase)||!(host.ws||host.virtualRoom))return null;return {key:host.id,listing:host.listing,room,watchId:room?peer.authorityId:peer.id===host.id?'host':peer.id};}
 presence(id){const u=this.users.get(id);if(!this.connected(u))return 'offline';const p=this.parties.get(u.party);if(p?.state==='queueing')return 'matchmaking';if(u.inMatch){const location=this.matchLocation(u);if(u.spectateLaunch||location?.room?.sim.players.get(location.watchId)?.spectating)return 'spectating';if(!location||location.listing.phase==='lobby')return 'lobby';return 'in-match';}return p?.members.length>1?'in-party':'lobby';}
 card(viewer,id){const identity=this.store.identities.get(id);if(!identity)return null;const u=this.users.get(id),p=this.parties.get(u?.party),available=this.connected(u)&&p?.state==='idle'&&!this.store.blocked(viewer,id);return {id,name:identity.profile.name,code:displayCode(identity.code),presence:this.presence(id),relationship:this.store.status(viewer,id),partySize:p?.members.length||0,spectatable:this.store.friends.get(viewer)?.has(id)&&!this.store.blocked(viewer,id)&&!!this.matchLocation(u),inviteable:available,joinable:available&&p.privacy==='open'&&p.members.length<PARTY_LIMIT,party:available&&p.privacy==='open'?p.id:undefined};}
 social(u,m={}){const friends=[...(this.store.friends.get(u.id)||[])].map(id=>this.card(u.id,id)).filter(Boolean),requests=[...this.store.requests.values()].filter(r=>r.from===u.id||r.to===u.id).map(r=>({...r,player:this.card(u.id,r.from===u.id?r.to:r.from),direction:r.to===u.id?'incoming':'outgoing'}));const offset=Math.max(0,Math.min(100000,Math.floor(Number(m.offset)||0))),eligible=[...this.users.values()].filter(v=>v.id!==u.id&&this.connected(v)&&!this.store.blocked(u.id,v.id)&&!this.store.friends.get(u.id)?.has(v.id)).sort((a,b)=>a.id.localeCompare(b.id));return {self:this.card(u.id,u.id),friends,requests,blocked:[...(this.store.blocks.get(u.id)||[])].map(id=>this.card(u.id,id)).filter(Boolean),online:eligible.slice(offset,offset+25).map(v=>this.card(u.id,v.id)),offset,total:eligible.length,invitations:[...this.invites.values()].filter(i=>i.to===u.id&&i.expires>Date.now()).map(i=>this.inviteView(i))};}
 limit(u,key,count,window){u.limits??=new Map();const now=Date.now(),times=(u.limits.get(key)||[]).filter(t=>now-t<window);if(times.length>=count)throw Error('Please wait before trying that again.');times.push(now);u.limits.set(key,times);}
 detachMember(u,{solo=true,reason='left'}={}){const p=this.parties.get(u.party);if(!p)return;if(p.state==='queueing')this.cancel(p,'Party membership changed.');p.members=p.members.filter(id=>id!==u.id);for(const [id,i]of this.invites)if(i.from===u.id||i.to===u.id||i.party===p.id&&p.members.length===0)this.invites.delete(id);for(const [id,t]of this.tickets)if(t.member===u.id&&!t.peer)this.tickets.delete(id);if(!p.members.length)this.parties.delete(p.id);else{if(p.leader===u.id)p.leader=p.members.find(id=>this.connected(this.users.get(id)))||p.members[0];if(!p.members.some(id=>this.users.get(id)?.inMatch)){p.state='idle';delete p.launch;}this.sync(p);}u.ready=false;if(!u.inMatch)delete u.joined;delete u.party;if(solo){this.create(u);this.sync(this.parties.get(u.party));}if(solo||reason==='timeout')this.send(u,{type:'party-notice',message:reason==='removed'?'You were removed from the party.':reason==='timeout'?'Your disconnected party membership expired.':'You left the party.'});this.changed();}
 leave(u,reason){this.detachMember(u,{reason});}
 cancel(p,reason='Matchmaking cancelled.'){this.relay.authority?.capacity?.release(p.id);const launchId=p.launch?.id,aborting=p.state==='queueing',waiting=aborting&&p.launch?.creating&&!p.launch.hostReady?[...this.parties.values()].filter(other=>other!==p&&other.state==='queueing'&&other.launch?.code===p.launch.code):[];for(const id of p.members){const u=this.users.get(id);if(aborting){const ticket=this.tickets.get(u.ticket),peer=this.relay.peers.get(ticket?.peer);if(peer?.authorityRoom)this.relay.authority.disconnect(peer);u.inMatch=false;delete u.matchPeer;}u.ready=false;delete u.joined;}p.state=p.members.some(id=>this.users.get(id)?.inMatch)?'playing':'idle';delete p.launch;for(const [t,a]of this.tickets)if(a.party===p.id&&(aborting||!a.peer))this.tickets.delete(t);for(const id of p.members)this.send(this.users.get(id),{type:'cancel',message:reason,launchId});this.sync(p);for(const other of waiting)this.cancel(other,'The pending match closed. Find a match again.');}
 attach(ws){let user,at=0,count=0,queue=Promise.resolve();const timeout=setTimeout(()=>{if(!user)ws.close();},10000);timeout.unref?.();
  ws.on('message',raw=>{let m;try{if(raw.length>8192)throw Error('Message too large');m=JSON.parse(raw);if(Date.now()-at>1000){at=Date.now();count=0;}if(++count>25)throw Error('Too many requests');}catch(e){ws.close(1008,e.message.slice(0,100));return;}
   // Serialize each session while awaiting durable writes, without blocking gameplay.
   queue=queue.then(async()=>{if(ws.readyState!==1)return;try{
    if(!user){if(m.type!=='hello'||m.version!==VERSION)throw Error('Refresh Ravelfront to connect.');const {identity,token}=this.store.identify(m.token,safeProfile(m.profile));await this.store.flush();if(ws.readyState!==1)return;user=this.users.get(identity.id);if(!user){user={id:identity.id,profile:identity.profile,ready:false,sessions:new Map(),seen:Date.now()};this.users.set(user.id,user);this.create(user);}user.sessions.set(ws,{seen:Date.now()});user.ws=ws;user.seen=Date.now();delete user.disconnectedAt;clearTimeout(timeout);this.send(user,{type:'hello',id:user.id,token,code:displayCode(identity.code)});if(this.relay.deployment)this.send(user,{type:'deployment',deployment:this.relay.deployment.snapshot()});this.send(user,{type:'public-match',match:this.relay.authority?.publicSummary()||null});this.sync(this.parties.get(user.party));return;}
    const session=user.sessions.get(ws);if(!session)return;session.seen=user.seen=Date.now();const result=this.command(user,m,ws);
    if(['profile','friend-send','friend-accept','friend-decline','friend-cancel','friend-remove','block','unblock'].includes(m.type))await this.store.flush();
    if(m.request&&ws.readyState===1)ws.send(JSON.stringify({type:'reply',request:m.request,result:result??true}));
   }catch(e){if(user&&ws.readyState===1)ws.send(JSON.stringify({type:'reply',request:m?.request,error:e.message}));else{if(ws.readyState===1&&e.code==='identity-missing')ws.send(JSON.stringify({type:'identity-unavailable',code:e.code,message:e.message}));ws.close(1008,String(e.message).slice(0,100));}}});
  });
  ws.on('pong',()=>{const session=user?.sessions.get(ws);if(session)session.seen=Date.now();});
  ws.on('close',()=>{clearTimeout(timeout);if(!user)return;user.sessions.delete(ws);if(user.ws===ws)user.ws=[...user.sessions.keys()].at(-1);if(!this.connected(user)){user.disconnectedAt=Date.now();user.ready=false;const p=this.parties.get(user.party);if(p?.state==='queueing')this.cancel(p,'A party member disconnected.');}this.sync(this.parties.get(user.party));});ws.on('error',()=>{});
 }
 inviteView(i){return {id:i.id,name:this.store.identities.get(i.from)?.profile.name||'Player',size:this.parties.get(i.party)?.members.length||0,expires:i.expires};}
 command(u,m,ws=u.ws){const p=this.parties.get(u.party),leader=()=>{if(p?.leader!==u.id)throw Error('Only the party leader can do that.');},idle=()=>{if(p?.state!=='idle'||u.inMatch)throw Error('Return to the lobby first.');};
  switch(m.type){
   case 'ping':return {presence:this.presence(u.id)};
   case 'profile':u.profile=safeProfile(m.profile);this.store.identities.get(u.id).profile=u.profile;this.store.save();this.relay.progression.leaderboardCache=null;this.sync(p);return;
   case 'leaderboards':this.limit(u,'leaderboards',30,60000);this.relay.progression.restoreLeaderboardViewer(m.progressToken,u.id);return this.relay.progression.leaderboards(u.id,{offset:m.offset});
   case 'social':this.limit(u,'browse',30,60000);return this.social(u,m);
   case 'online':this.limit(u,'browse',30,60000);return this.social(u,m).online;
   case 'lookup':{this.limit(u,'lookup',12,60000);const code=normalizeFriendCode(m.code);if(!/^[A-HJ-NP-Z2-9]{10}$/.test(code))throw Error('Enter a valid Friend Code, for example AB7KQ-4M2QX.');const id=this.store.codes.get(code);if(!id||this.store.blocked(u.id,id))throw Error('Friend Code not found or player unavailable.');if(id===u.id)throw Error('That is your own Friend Code.');return this.card(u.id,id);}
   case 'friend-send':case 'friend-accept':case 'friend-decline':case 'friend-cancel':case 'friend-remove':case 'block':case 'unblock':{this.limit(u,m.type==='friend-send'?'requests':'relations',m.type==='friend-send'?10:30,60000);const result=this.store.friendAction(u.id,m.type,m.id);if(m.type==='block')for(const [id,i]of this.invites)if(i.from===u.id&&i.to===m.id||i.from===m.id&&i.to===u.id)this.invites.delete(id);this.changed();if(m.type==='friend-send'&&result.status==='outgoing')this.send(this.users.get(m.id),{type:'friend-request',name:u.profile.name});return result;}
   case 'privacy':leader();idle();p.privacy=m.value==='open'?'open':'invite';this.sync(p);return;
   case 'select':{leader();idle();if(!['royale','ffa'].includes(m.mode))throw Error('Choose Free For All or Frontier Royale.');const size=m.mode==='royale'&&[2,4].includes(m.teamSize)?m.teamSize:1;if(m.mode==='royale'&&p.members.length>size)throw Error('Choose '+(p.members.length>2?'Squads':'Duos or Squads')+' for this party, or leave for Solo.');const fill=m.teamFill??m.duoFill??true;p.selection={mode:m.mode,teamSize:size,teamFill:fill!==false,duoFill:fill!==false};for(const id of p.members)this.users.get(id).ready=false;this.sync(p);return;}
   case 'ready':idle();u.ready=!!m.value;this.sync(p);return;
   case 'invite':{idle();this.limit(u,'invites',10,60000);if(p.members.length>=PARTY_LIMIT)throw Error('This party is full (4 players).');const to=this.users.get(m.id),dest=this.parties.get(to?.party);if(!this.connected(to))throw Error('Player is offline.');if(to.party===p.id)throw Error('Player is already in your party.');if(this.store.blocked(u.id,to.id))throw Error('Player unavailable.');if(dest?.state!=='idle'||to.inMatch)throw Error('That player must return to the lobby.');if([...this.invites.values()].some(i=>i.to===to.id&&i.party===p.id&&i.expires>Date.now()))throw Error('An invitation is already pending.');const invite={id:randomUUID(),from:u.id,to:to.id,party:p.id,expires:Date.now()+INVITE_TTL};this.invites.set(invite.id,invite);this.send(to,{type:'invite',invite:this.inviteView(invite)});this.changed();return;}
   case 'accept':case 'decline':{const invite=this.invites.get(m.id);if(!invite||invite.to!==u.id||invite.expires<Date.now())throw Error('Invitation expired.');if(m.type==='accept'){if(this.store.blocked(u.id,invite.from))throw Error('Invitation unavailable.');this.join(u,invite.party);}this.invites.delete(m.id);this.changed();return;}
   case 'join':{const dest=this.parties.get(m.id);if(dest?.privacy!=='open')throw Error('This party is invite-only.');return this.join(u,m.id);}
   case 'leave':if(p.members.length<=1)throw Error('You are already in your own party.');this.leave(u);return;
   case 'kick':{leader();if(p.state==='playing')throw Error('Return to the lobby first.');const v=this.users.get(m.id);if(!v||v.party!==p.id||v.id===u.id)throw Error('Invalid member.');this.leave(v,'removed');return;}
   case 'returned':if(u.inMatch&&u.matchSession!==ws&&u.sessions.has(u.matchSession)&&this.relay.peers.get(u.matchPeer)?.ws)throw Error('This player is in a match in another tab.');this.relay.authority?.capacity?.release(p.id);if(u.spectateLaunch){this.relay.authority?.capacity?.release(u.spectateLaunch.id);this.tickets.delete(u.ticket);delete u.spectateLaunch;}this.tickets.delete(u.ticket);delete u.ticket;u.ready=false;u.inMatch=false;delete u.matchPeer;delete u.joined;if(p.state==='queueing')this.cancel(p,'Party returned to the lobby.');else{if(!p.members.some(id=>this.users.get(id).inMatch)){p.state='idle';delete p.launch;}this.sync(p);}return;
   case 'cancel':leader();if(p.state==='playing')throw Error('Return to the lobby before finding another match.');this.cancel(p);return;
   case 'queue':leader();idle();return queueMatch(this,u,m);
   case 'spectate-friend':if(u.inMatch||p.state==='queueing')throw Error('Return to the lobby before spectating.');return spectateFriend(this,u,m);
   case 'host-ready':{let publicAdmission;leader();if(!p.launch||p.launch.id!==m.id||!p.launch.creating||!p.launch.hostRun)throw Error('Launch is not a private player host.');{const host=this.relay.peers.get(`yolk-yard-v${VERSION}-${p.launch.code}`);if(!host||host.virtualRoom)throw Error('Match host is not connected.');host.rewardPublic=!!p.launch.recurring;if(p.launch.recurring){const admission=this.claim(u.ticket,host.id,host.id);publicAdmission=this.relay.publicHost.admission(host,admission);if(!publicAdmission)throw Error('Public host admission failed.');}}this.claim(u.ticket,`yolk-yard-v${VERSION}-${p.launch.code}`,`yolk-yard-v${VERSION}-${p.launch.code}`);p.launch.hostReady=true;this.dispatch(p,true);if(p.launch.recurring)for(const waiting of this.parties.values())if(waiting!==p&&waiting.state==='queueing'&&waiting.launch?.recurring)this.dispatch(waiting);return publicAdmission||true;}
   case 'joined':{if(u.spectateLaunch?.id===m.id){const t=this.tickets.get(u.ticket);if(!t?.peer||!this.relay.peers.has(t.peer))throw Error('Spectator reservation expired.');u.inMatch=true;u.matchPeer=t.peer;u.matchCode=t.code;u.matchSession=ws;p.state='playing';this.sync(p);return;}const ticket=this.tickets.get(u.ticket);if(!p.launch||m.id!==p.launch.id||!ticket?.peer||!this.relay.peers.has(ticket.peer))throw Error('Match reservation was not claimed.');u.joined=m.id;u.inMatch=true;u.matchPeer=ticket.peer;u.matchCode=ticket.code;u.matchSession=ws;if(p.members.every(id=>this.users.get(id).joined===m.id))p.state='playing';this.sync(p);return;}
   case 'failed':if(u.spectateLaunch?.id===m.id){this.relay.authority?.capacity?.release(u.spectateLaunch.id);this.tickets.delete(u.ticket);delete u.spectateLaunch;return;}if(p.launch?.id===m.id)this.cancel(p,String(m.reason||'Unable to join together.').slice(0,120));return;
   default:throw Error('Unknown social action.');
  }
 }
 join(u,id){const dest=this.parties.get(id),old=this.parties.get(u.party);if(!dest||dest===old||dest.state!=='idle'||old?.state!=='idle'||u.inMatch)throw Error('Party is unavailable.');if(dest.members.length>=PARTY_LIMIT)throw Error('This party is full (4 players).');if(dest.members.some(member=>this.store.blocked(u.id,member)))throw Error('Party is unavailable.');this.detachMember(u,{solo:false});u.party=id;u.ready=false;dest.members.push(u.id);if(dest.selection.mode==='royale'&&dest.selection.teamSize<dest.members.length)dest.selection.teamSize=dest.members.length>2?4:2;for(const member of dest.members)this.users.get(member).ready=false;this.sync(dest);}
 dispatch(p,skipHost=false){for(const id of p.members){if(skipHost&&id===p.leader)continue;const u=this.users.get(id);this.send(u,{type:'launch',launch:{...p.launch,host:false,ticket:u.ticket}});}}
 publicAdmission(t){return {partyId:t.reservationId||t.party,memberId:t.member,partySize:t.partySize,teamFill:t.teamFill,duoFill:t.teamFill,teamSize:t.teamSize,...(t.spectator?{spectator:true,publicSpectator:!!t.publicSpectator,watchId:t.watchId}:{}),...(t.recurring?{recurring:true}:{}),...(t.hostRun?{hostRun:true}:{}),...(t.friend?{friendSpectator:true}:{})};}
 claim(token,peer,room){const t=this.tickets.get(token);if(t?.friend){const viewer=this.users.get(t.member),friend=this.users.get(t.friend);if(!this.store.friends.get(t.member)?.has(t.friend)||this.store.blocked(t.member,t.friend)||this.matchLocation(friend)?.key!==room||!viewer)return null;}if(!t||t.expires<Date.now()||room!==`yolk-yard-v${VERSION}-${t.code}`||t.peer&&t.peer!==peer)return null;t.peer=peer;t.claimedAt=Date.now();return this.publicAdmission(t);}
 sweep(){const now=Date.now();for(const [id,i]of this.invites)if(i.expires<now){this.invites.delete(id);this.changed();}for(const [id,t]of this.tickets)if(t.expires<now)this.tickets.delete(id);for(const u of [...this.users.values()]){for(const [ws,s]of u.sessions){if(now-s.seen>HEARTBEAT_TIMEOUT)ws.terminate();else if(ws.readyState===1&&now-(s.lastPing||0)>15000){s.lastPing=now;ws.ping();}}if(!this.connected(u)&&u.disconnectedAt&&now-u.disconnectedAt>RECONNECT_GRACE){this.detachMember(u,{solo:false,reason:'timeout'});this.users.delete(u.id);continue;}const current=this.presence(u.id);if(current!==u.lastPresence){u.lastPresence=current;this.changed();}if(u.inMatch&&!this.relay.peers.has(u.matchPeer)){u.inMatch=false;const p=this.parties.get(u.party);if(p&&!p.members.some(id=>this.users.get(id)?.inMatch)){p.state='idle';delete p.launch;}this.sync(p);}}for(const p of this.parties.values())if(p.state==='queueing'&&now-p.launch?.created>35000)this.cancel(p,'Matchmaking timed out. Try again.');}
 close(){clearInterval(this.timer);clearTimeout(this.changeTimer);for(const u of this.users.values())for(const ws of u.sessions.keys())ws.close(1001,'Server restarting');return this.store.flush();}
}
