import test from 'node:test';
import assert from 'node:assert/strict';
import {RoyaleSimulation} from '../src/royale.js';
import {ROYALE_MAP} from '../src/royale-map.js';
import {MATERIALS,inventory,placement,validPlacement,rebuildMap,buildingTick,damageObject,editBuilding,swingPickaxe,pieceBoxes,applyBuildState,toggleDoor} from '../src/building.js';
import {canStand,wallDistance,movePlayer} from '../src/physics.js';
function setup(){const s=new RoyaleSimulation({bots:0,capacity:2});s.addPlayer('a',{});s.addPlayer('b',{});s.phase='playing';s.stage='active';s.map={theme:'royale',size:256,boxes:[]};s.worldBoxes=[];s.worldDamage={};s.builds=[];s.time=1;for(const p of s.players.values())Object.assign(p,{x:0,y:0,z:0,flight:'ground',grounded:true,yaw:0,pitch:0,health:100,slot:0,inventory:inventory(),materials:{wood:100,brick:100,metal:100}});s.players.get('b').x=40;return s;}
test('world materials cover every authored collision object',()=>{assert.ok(ROYALE_MAP.boxes.length>1000);for(const b of ROYALE_MAP.boxes){assert.ok(MATERIALS[b.material]);assert.ok(b.objectId);}assert.ok(new Set(ROYALE_MAP.boxes.map(b=>b.material)).size===3);});
test('pickaxe remains in first slot through drops, swaps, fills and selection',()=>{const s=setup(),p=s.players.get('a');for(const action of ['inventory-drop-0','inventory-drop-one-0','inventory-swap-0-5','inventory-swap-5-0','inventory-split-0'])s.playerAction(p.id,action);assert.equal(p.inventory[0].id,'pickaxe');s.dropSlot(p,0);assert.equal(p.inventory[0].id,'pickaxe');s.playerAction(p.id,'inventory-select-0');assert.equal(p.slot,0);});
test('authoritative build costs, duplicate prevention, collision and editing',()=>{const s=setup(),p=s.players.get('a');const i={buildMode:true,buildType:'wall',buildMaterial:'wood',fire:true};buildingTick(s,p,i);assert.equal(s.builds.length,1);assert.equal(p.materials.wood,90);s.time++;buildingTick(s,p,i);assert.equal(s.builds.length,1);assert.equal(p.materials.wood,90);const b=s.builds[0];assert.ok(wallDistance(s.map,{x:0,y:1,z:0},{x:0,y:0,z:-1},9)<9);assert.equal(editBuilding(s,s.players.get('b'),'build-edit-18-'+b.id),false);assert.equal(editBuilding(s,p,'build-edit-18-'+b.id),true);p.z=-4;assert.equal(toggleDoor(s,p),true);assert.equal(wallDistance(s.map,{x:0,y:1,z:0},{x:0,y:0,z:-1},9),9);assert.equal(editBuilding(s,p,'build-edit-511-'+b.id),false);assert.ok(s.events.every(e=>Number.isInteger(e.id)),'Build acknowledgments must not overwrite event sequence IDs');});
test('unsupported builds and player overlap rejected; stairs can be climbed',()=>{const s=setup(),p=s.players.get('a');assert.equal(validPlacement({...placement(p,'floor'),y:40},s.map,[]),'Needs support');const proposal={id:'ramp',type:'stairs',x:0,y:0,z:0,rotation:0,mask:0,material:'wood'};assert.equal(validPlacement(proposal,s.map,[],[p]),'Player in the way');s.builds=[proposal];rebuildMap(s);Object.assign(p,{x:0,y:0,z:3,yaw:0});for(let i=0;i<65;i++)movePlayer(p,{forward:1,yaw:0,pitch:0},s.map,1/60);assert.ok(p.y>2,p.y);});
test('harvesting is range limited, rate limited, capped and removes collision',()=>{const s=setup(),p=s.players.get('a');const box={objectId:'tree',kind:'tree',x:0,y:0,z:-3,w:1,d:1,h:5,material:'wood'};s.worldBoxes=[box];rebuildMap(s);p.materials.wood=995;swingPickaxe(s,p);assert.equal(p.materials.wood,999);assert.equal(s.worldDamage.tree.health,s.worldDamage.tree.maxHealth-50);swingPickaxe(s,p);assert.equal(s.worldDamage.tree.health,s.worldDamage.tree.maxHealth-50);for(let i=0;i<8;i++){s.time++;swingPickaxe(s,p);}assert.equal(s.worldDamage.tree.destroyed,true);assert.equal(s.map.boxes.length,0);});
test('destroying support collapses descendants and snapshot map reproduces destruction',()=>{const s=setup(),p=s.players.get('a');buildingTick(s,p,{buildMode:true,buildType:'wall',buildMaterial:'metal',fire:true});const base=s.builds[0];s.builds.push({...base,id:'upper',y:4});rebuildMap(s);damageObject(s,s.map.boxes[0],1000);assert.equal(s.builds.length,0);const remote={...s.map,boxes:[]};applyBuildState(remote,{matchId:'m',round:1,buildVersion:1,builds:[base],worldDamage:{}});assert.ok(remote.boxes.length);applyBuildState(remote,{matchId:'m',round:2,buildVersion:1,builds:[],worldDamage:{}});assert.equal(remote.boxes.length,0);});
test('checkpoint preserves construction, damage, material banks and pickaxe',()=>{const s=setup(),p=s.players.get('a');buildingTick(s,p,{buildMode:true,buildType:'wall',buildMaterial:'brick',fire:true});const restored=new RoyaleSimulation().restore(s.checkpoint());assert.equal(restored.builds.length,1);assert.equal(restored.players.get('a').materials.brick,90);assert.equal(restored.players.get('a').inventory[0].id,'pickaxe');assert.ok(restored.map.boxes.some(b=>b.buildId));assert.equal(s.checkpoint().worldBoxes,undefined);});
