import test from 'node:test';
import assert from 'node:assert/strict';
import {COMBAT_PROFILES,updateCombatAccuracy,firedAccuracy,criticalHit,falloffAt,pelletOffsets} from '../src/combat.js';
import {gun,weapon} from '../src/data.js';
import {Simulation} from '../src/simulation.js';
import {RoyaleSimulation} from '../src/royale.js';
import {teammates} from '../src/teams.js';
function arena(id='sprinter'){const s=new Simulation({mode:'ffa',bots:0,seed:3}),a=s.addPlayer('a',{name:'A',weapon:id}),b=s.addPlayer('b',{name:'B'});s.startRound();s.map={size:500,boxes:[]};s.time=10;Object.assign(a,{x:0,y:0,z:10,health:100,grounded:true,yaw:0,pitch:0,aim:true,shieldUntil:0,ammo:[100,10],accuracyState:[{spread:0},{}]});Object.assign(b,{x:0,y:0,z:0,health:100,shieldUntil:0,spectating:false});return {s,a,b};}
test('all fictional profiles have intentional range, rarity, build damage and firing rules',()=>{assert.equal(Object.keys(COMBAT_PROFILES).length,11);for(const id of Object.keys(COMBAT_PROFILES)){const w=weapon(id),high=gun({slot:1,inventory:[null,{id,weapon:true,rarity:4}]});assert.ok(w.damage>0&&w.buildDamage>0&&w.range>0&&w.magazine>0);assert.ok(high.damage>w.damage&&high.reload<w.reload);assert.equal(high.critical,w.critical);assert.equal(high.pellets,w.pellets);assert.deepEqual(high.falloff,w.falloff);}assert.ok(falloffAt(weapon('scatter'),35)<.1);assert.ok(falloffAt(weapon('needle'),350)===1);});
test('upper shell is the only critical region and cosmetics do not change it',()=>{const p={y:0};assert.equal(criticalHit({y:.9},p,weapon('sprinter')),false);assert.equal(criticalHit({y:1.5},p,weapon('sprinter')),true);assert.equal(criticalHit({y:1.5},p,weapon('thumper')),false);assert.equal(criticalHit({y:.75},{y:0,bodyScale:.5},weapon('sprinter')),true);});
test('host hitscan endpoint, accepted damage and head feedback agree',()=>{const {s,a,b}=arena('anchor');a.pitch=Math.atan2(1.5-1.43,10);s.fire(a);assert.equal(s.projectiles.length,0);const hit=s.events.find(e=>e.type==='hit'),shot=s.events.findLast(e=>e.type==='shot');assert.ok(hit.precision);assert.ok(Math.abs(hit.amount-weapon('anchor').damage*1.8)<.001);assert.ok(shot.shots[0].end.z<1);});
test('cover blocks hitscan and build damage uses its own weapon value',()=>{const {s,a,b}=arena();s.map.boxes=[{x:0,y:0,z:5,w:5,h:5,d:.01}];let structural=0;s.damageWorld=(box,damage)=>structural+=damage;s.fire(a);assert.equal(b.health,100);assert.equal(structural,weapon('sprinter').buildDamage);assert.equal(s.events.filter(e=>e.type==='hit').length,0);});
test('pellets are deterministic and one pellet cannot apply the whole shot',()=>{const points=pelletOffsets(10,.15,42);assert.deepEqual(points,pelletOffsets(10,.15,42));assert.ok(points.every(p=>Math.hypot(p.yaw,p.pitch)<=.07500001));const {s,a,b}=arena('scatter');a.pitch=Math.atan2(.9-1.43,10);s.fire(a);const total=s.events.filter(e=>e.type==='hit').reduce((v,e)=>v+e.amount,0);assert.ok(total>0&&total<=85);assert.equal(a.ammo[0],99);assert.equal(s.events.findLast(e=>e.type==='shot').shots.length,10);});
test('FSA needs settled ADS; movement, bloom and recoil recover; scopes stay stable',()=>{const p={aim:true,grounded:true,slot:0},w=weapon('sprinter'),a={};for(let n=0;n<30;n++)updateCombatAccuracy(p,w,a,1/60,n/60,0);assert.equal(a.firstShot,true);firedAccuracy(p,w,a,.5);assert.ok(a.recoilPitch>0&&a.bloom>0);updateCombatAccuracy(p,w,a,.1,.6,5);assert.ok(a.spread>w.adsSpread);for(let n=0;n<120;n++)updateCombatAccuracy(p,w,a,1/60,.6+n/60,0);assert.equal(a.firstShot,true);assert.ok(a.recoilPitch<.0001);for(const id of ['needle','anchor','peeper']){const s={};updateCombatAccuracy({...p,grounded:false},weapon(id),s,.016,5,12);assert.equal(s.spread,0);}});
test('lag compensation is host bounded and never trusts arbitrary damage or teleports',()=>{const {s,a,b}=arena();s.remoteInputs.set(a.id,{});s.inputs.set(a.id,{shotTime:-1000,damage:99999});s.poseHistory=new Map([[b.id,[{time:9.7,x:-3,y:0,z:0},{time:9.82,x:-1,y:0,z:0},{time:10,x:0,y:0,z:0}]]]);assert.equal(s.shotPose(b,a,weapon('sprinter')).x,-1);b.x=40;assert.equal(s.shotPose(b,a,weapon('sprinter')),b);});
test('Duo Fill pairs humans and bot teammates while No Fill remains alone',()=>{const s=new RoyaleSimulation({teamSize:2,capacity:8,bots:7,fill:true,seed:3});const h=s.addPlayer('h',{name:'Host'});s.startRound();const fill=s.admitPlayer('f',{name:'Fill'},{partyId:'f',partySize:1,duoFill:true});assert.equal(fill.team,h.team);const solo=s.admitPlayer('n',{name:'Solo'},{partyId:'n',partySize:1,duoFill:false});assert.ok(![...s.players.values()].some(p=>teammates(s.options,solo,p)));const restored=new RoyaleSimulation().restore(s.checkpoint());assert.equal(restored.players.get('f').team,restored.players.get('h').team);assert.equal(restored.options.teamSize,2);});
