import test from 'node:test';import assert from 'node:assert/strict';
import {RoyaleSimulation} from '../src/royale.js';import {SEASON,publicWindow,rigCharges} from '../src/season-one.js';import {bossInput,useSeasonItem,smokeBlocks,seasonInteract} from '../src/season-world.js';import {weapon,gun} from '../src/data.js';import {movePlayer,canStand} from '../src/physics.js';import {fallDamage} from '../src/airborne.js';import {SnapshotEncoder,SnapshotDecoder} from '../src/snapshot-codec.js';import {Simulation} from '../src/simulation.js';
function battle(){const s=new RoyaleSimulation({seed:31,bots:3,capacity:4});const p=s.addPlayer('tester',{name:'Tester'});s.startRound();assert.equal(s.beginBattle(),true);Object.assign(p,{flight:'ground',grounded:true,shieldUntil:0,x:0,y:0,z:0});return {s,p,b:s.players.get(SEASON.boss.id)};}
test('Eastern public hours respect 7am/7pm, including DST and winter boundaries',()=>{for(const [date,open]of [['2026-10-02T10:59:59Z',false],['2026-10-02T11:00:00Z',true],['2026-10-02T22:59:59Z',true],['2026-10-02T23:00:00Z',false],['2026-12-02T11:59:00Z',false],['2026-12-02T12:00:00Z',true],['2026-12-03T00:00:00Z',false]])assert.equal(publicWindow(Date.parse(date)).open,open,date);});
test('boss is a collision-valid NPC outside the 48-seat contestant/win roster, drops once, normal legendary stats',()=>{const {s,p,b}=battle();assert.ok(b?.boss);assert.ok(canStand(s.map,b));assert.equal(b.contestant,false);assert.equal(b.health,600);assert.equal(b.shield,400);assert.equal(gun(b).damage,gun({...b,boss:false}).damage);const total=s.alive;s.damage(b,p,401,'Sprinter',true,1);assert.equal(b.health,599);assert.equal(b.shield,0);assert.equal(p.kills,0);s.damage(b,p,999,'Sprinter',false,2);s.damage(b,p,999,'Sprinter',false,2);assert.equal(s.loot.filter(i=>i.id==='jumpRig').length,1);assert.equal(s.alive,total);assert.equal(p.kills,0);const restored=new RoyaleSimulation().restore(s.checkpoint());assert.equal(restored.players.get(b.id).bossDefeated,true);assert.equal(restored.loot.filter(i=>i.id==='jumpRig').length,1);});
test('mythic has three charges, fixed recharge/cooldown, persistent drop state, protected landing',()=>{const {s,p}=battle();const item={id:'jumpRig',count:1,rarity:5};for(let i=0;i<3;i++){s.time=100+i*2;assert.equal(useSeasonItem(s,p,item),true);assert.equal(useSeasonItem(s,p,item),false);}assert.equal(item.charges,0);assert.equal(useSeasonItem(s,p,item),false);assert.equal(p.fall.immune,true);assert.equal(fallDamage({distance:40,immune:p.fall.immune}),0);assert.equal(rigCharges(item,112),1);assert.equal(rigCharges(item,136),3);p.inventory[1]=item;p.slot=1;s.dropSlot(p);assert.equal(s.loot.find(l=>l.id==='jumpRig').charges,3);});
test('boss reaction and firing require line of sight, ordinary ammo and cadence',()=>{const {s,p,b}=battle();Object.assign(p,{x:b.x,y:b.y,z:b.z-4});b.yaw=0;s.time=10;bossInput(s,b);assert.equal(bossInput(s,b).fire,false);s.time=10.9;const input=bossInput(s,b);if(input.fire){const before=b.ammo[1];assert.equal(s.fire(b),true);assert.equal(b.ammo[1],before-1);assert.equal(s.fire(b),false);}});
test('ammo/material drops conserve totals, block immediate self pickup and reject forged types',()=>{const {s,p}=battle();Object.assign(p,{x:s.map.floorLoot[0].x,y:s.map.floorLoot[0].y,z:s.map.floorLoot[0].z});p.bank.medium=101;s.playerAction(p.id,'inventory-supply-medium-half');assert.equal(p.bank.medium,50);const drop=s.loot.find(i=>i.droppedBy===p.id);assert.equal(drop.count,51);assert.equal(s.takeLoot(p,drop),false);s.time+=3;Object.assign(p,{x:drop.x,y:drop.y,z:drop.z});s.takeLoot(p,drop);assert.equal(p.bank.medium,101);p.materials.wood=121;s.playerAction(p.id,'inventory-supply-wood-all');assert.equal(p.materials.wood,0);s.playerAction(p.id,'inventory-supply-__proto__-all');assert.equal(p.health,100);});
test('relay broadcasts risk/reward markers, smoke blocks only vision, scanner snapshots work',()=>{const {s,p,b}=battle();assert.ok(s.relays.length);const r=s.relays[0];Object.assign(p,{x:r.x,y:r.y,z:r.z,lastDamage:-100});s.time=100;for(let i=0;i<31;i++)seasonInteract(s,p,{interact:true},.1);assert.ok(r.cooldown>s.time);assert.ok(s.markers.some(m=>m.global));s.smokes=[{id:1,x:0,y:1,z:0,radius:4.5,until:120}];assert.ok(smokeBlocks(s,{x:-10,y:1,z:0},{x:10,y:1,z:0}));const enc=new SnapshotEncoder(),dec=new SnapshotDecoder();const msg={state:s.snapshot()};const wire=enc.encode(msg);const copy=dec.decode(JSON.parse(JSON.stringify(wire.frame)));assert.deepEqual(copy.state.royale.smokes,s.snapshot().royale.smokes);assert.ok(copy.state.players.find(p=>p.boss));});
test('flight speeds are reduced and terrain sliding starts from rest and stays capped',()=>{const map={size:256,boxes:[],theme:'royale'},p={health:100,x:0,y:100,z:0,yaw:0,pitch:0,flight:'glide',grounded:false,vy:0};movePlayer(p,{yaw:0,forward:1},map,1/60);assert.ok(Math.abs(p.z+16/60)<1e-8);assert.equal(p.vy,-4.8);});
test('training remains on island, replenishes supplies, allows real target damage, no build in Zero Build',()=>{const s=new RoyaleSimulation({training:true,session:'offline',bots:2,capacity:4}),p=s.addPlayer('trainer',{name:'Trainer'});s.startRound();s.time=9999;s.advanceWarmupClock();assert.equal(s.stage,'spawn-island');s.tick(1/60);assert.equal(p.inventory[3].id,'jumpRig');s.playerAction(p.id,'training-weapon-needle');assert.equal(p.inventory[1].id,'needle');const b=[...s.players.values()].find(p=>p.bot);b.shieldUntil=0;s.damage(b,p,25,'Needle');assert.equal(b.health,75);const z=new RoyaleSimulation({building:false});assert.equal(z.options.building,false);assert.equal(new RoyaleSimulation({recurring:true,building:false}).options.building,true);});
test('restricted private arena pools survive respawns/profile changes',()=>{const s=new Simulation({weaponPool:'precision'}),p=s.addPlayer('a',{name:'Operator',weapon:'zipper'});assert.equal(p.weapon,'anchor');s.setProfile(p.id,{name:'Operator',weapon:'scatter'});s.spawn(p);assert.equal(p.weapon,'anchor');});

test('holding crouch starts a real downhill slide without sprint and caps acceleration',()=>{const map={size:100,boxes:[],theme:'royale',terrain:{size:100,cell:100,n:3,heights:new Float32Array([80,40,0,80,40,0,80,40,0])}},p={health:100,x:0,y:40,z:0,yaw:0,pitch:0,flight:'ground',grounded:true,vy:0,weapon:'sprinter'};movePlayer(p,{crouch:true},map,1/60);assert.equal(p.sliding,true);assert.ok(p.slideVX>0);for(let n=0;n<300;n++)movePlayer(p,{crouch:true},map,1/60);assert.ok(p.x>20);assert.ok(Math.hypot(p.slideVX,p.slideVZ)<=SEASON.slide.cap+.001);assert.equal(p.sliding,true);movePlayer(p,{crouch:false},map,1/60);assert.equal(p.sliding,false);});
