import {html} from './lobby-ui.js';
import {careerSummary,CAREER_MODES} from './career.js';
const number=n=>n.toLocaleString('en-US');
const date=time=>time?new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(time*1000)):'Date unavailable';
export function careerMarkup({stats,wallet,profile,selected='all',portrait}){
 const c=careerSummary(stats,wallet,selected);
 const tile=(label,value,note='')=>`<article class="career-stat"><small>${label}</small><strong>${value}</strong><span>${note}</span></article>`;
 return `<div class="career-page"><section class="career-hero"><div class="career-hero-copy"><span class="eyebrow">PERSONNEL DOSSIER / RAVEL COAST</span><h1>YOUR FRONT.<br>YOUR LEGACY.</h1><p>${html(profile.name)} · Every deployment leaves a mark.</p><div class="career-grade"><span class="career-insignia" aria-hidden="true">R</span><div><small>CAREER GRADE</small><strong>${c.grade}</strong><span>${number(c.score)} career score</span></div></div><div class="career-progress" role="progressbar" aria-label="Career grade progress" aria-valuenow="${Math.round(c.progress)}" aria-valuemin="0" aria-valuemax="100"><i style="width:${c.progress}%"></i></div><p class="career-grade-note">${c.nextGrade?number(c.needed)+' score to '+c.nextGrade:'Highest career grade reached'} · Personal progression, not a competitive rank.</p></div><img src="${portrait}" alt="${html(profile.name)} equipped operator"><div class="career-hero-record"><small>FRONTIER ROYALE RECORD</small><strong>${c.best?'#'+c.best:'—'}</strong><span>${c.best?'Best recorded placement':'Complete a verified Royale match'}</span></div></section>
 <section class="career-performance"><div class="hub-section-heading"><div><span class="eyebrow">VERIFIED COMBAT RECORD</span><h2>Deployment statistics</h2></div><label class="career-mode-label">Mode<select id="career-mode" aria-label="Career mode">${Object.entries(CAREER_MODES).map(([id,name])=>`<option value="${id}" ${selected===id?'selected':''}>${name}</option>`).join('')}</select></label></div><div class="career-stats">${tile('MATCHES',number(c.matches))}${tile('VICTORIES',number(c.wins))}${tile('ELIMINATIONS',number(c.kills))}${tile('ASSISTS',number(c.assists))}${tile('WIN RATE',c.winRate.toFixed(1)+'%')}${tile('ELIMS / MATCH',c.perMatch.toFixed(1),'Not a kill/death ratio')}</div></section>
 <div class="career-columns"><section class="career-history"><div class="hub-section-heading"><div><span class="eyebrow">AFTER-ACTION ARCHIVE</span><h2>Recent deployments</h2></div><span>Last ${c.history.length} recorded</span></div>${c.history.length?`<div class="career-history-list">${c.history.map(r=>`<article class="career-match"><div class="career-result ${r.won?'won':''}">${r.won?'VICTORY':r.place?'#'+r.place:'COMPLETE'}</div><div><strong>${CAREER_MODES[r.mode]||'Arena'}</strong><small>${date(r.time)}${r.custom?' · Private match':''}</small></div><div class="career-match-combat"><b>${r.kills} ELIMS</b><small>${r.assists} assists</small></div><span class="career-match-marks">+${number(r.marks)} Marks</span></article>`).join('')}</div>`:`<div class="career-empty"><span aria-hidden="true">◈</span><h3>Your next chapter starts here.</h3><p>${selected==='all'?'Your existing totals are preserved. Detailed history begins with verified matches completed after this update.':'No recorded deployments for this mode yet.'}</p><button data-action="lobby-home">GO TO PLAY →</button></div>`}<p class="career-footnote">History keeps the latest 50 verified deployments on this browser. No invented historical matches.</p></section>
 <aside class="career-service"><span class="eyebrow">SERVICE INVENTORY</span><h2>Beyond the battlefield</h2><div><strong>${number(c.owned)}</strong><span>Owned cosmetics</span></div><div><strong>${number(c.received)}</strong><span>Total Marks received, including starter grants</span></div><button data-action="locker">VIEW YOUR LOCKER →</button><button data-action="item-shop">VISIT ITEM SHOP →</button><p>Career score: 100 per match, 20 per elimination, 10 per assist and 200 per victory. It does not award extra Marks or affect matchmaking.</p></aside></div>
 <section class="career-milestones"><div class="hub-section-heading"><div><span class="eyebrow">PERSONAL SERVICE GOALS</span><h2>Milestones</h2></div><span>${c.milestones.filter(m=>m.complete).length} / ${c.milestones.length} complete</span></div><div class="career-milestone-grid">${c.milestones.map(m=>`<article class="career-milestone ${m.complete?'complete':''}"><span class="milestone-symbol" aria-hidden="true">${m.complete?'✓':'◇'}</span><h3>${m.name}</h3><p>${m.description}</p><div class="career-progress"><i style="width:${m.percent}%"></i></div><small>${m.complete?'COMPLETED':number(m.current)+' / '+number(m.target)}</small></article>`).join('')}</div></section><p class="career-footnote">Verified eligible online results count. Practice and Spawn Island do not. Keep browser data to preserve your career and collection; there is no cross-device career account.</p></div>`;
}
