import { safeName } from './moderation.js';
import {OPTICS} from './weapon-presentation.js';
import {cosmeticProfile} from './shop-catalog.js';
// The rebuilt island and movement model must not mix with older clients.
export const VERSION = 15;
export const WEAPONS = [
  {
    id: "sprinter",
    basedOn: "EggK-47",
    reloadEmpty: 3.433333333333333,
    ammoPickup: 30,
    automatic: true,
    spreadMax: 0.15,
    shotBloom: 0.05,
    spreadRecovery: 0.025,
    aimSpread: 0.5,
    movementSpread: 1,
    muzzle: 0.9,
    sightY: 0.285,
    boltSpeed: 45.0,
    gravity: 0,
    optic: "reflex",
    name: "Sprinter",
    role: "ASSAULT",
    desc: "A steady all-rounder. Fast, accurate, dependable.",
    damage: 30,
    interval: 0.1,
    magazine: 30,
    reserve: 240,
    reload: 2.6666666666666665,
    spread: 0.03,
    pellets: 1,
    speed: 7.4,
    range: 20,
    color: 0xf8b829,
    size: 1,
    zoom: 65,
  },
  {
    id: "scatter",
    basedOn: "Scrambler",
    reloadEmpty: 2.6,
    ammoPickup: 8,
    automatic: false,
    spreadMax: 0.16,
    shotBloom: 0.17,
    spreadRecovery: 0.02,
    aimSpread: 0.6,
    movementSpread: 0.2,
    muzzle: 0.9,
    sightY: 0.22,
    boltSpeed: 30,
    gravity: 0,
    optic: "iron",
    name: "Scatter",
    role: "SCATTER",
    desc: "Get close. One wide burst, plenty of punch.",
    damage: 8.5,
    interval: 0.26666666666666666,
    magazine: 2,
    reserve: 24,
    reload: 2.6,
    spread: 0.13,
    pellets: 20,
    speed: 7.4,
    range: 8,
    color: 0xf47b57,
    size: 1.1,
    zoom: 70,
  },
  {
    id: "needle",
    basedOn: "Crackshot",
    reloadEmpty: 2.4,
    ammoPickup: 4,
    automatic: false,
    spreadMax: 0.35,
    shotBloom: 0.1,
    spreadRecovery: 0.023,
    aimSpread: 0.5,
    movementSpread: 1.3,
    muzzle: 1.1,
    sightY: 0.285,
    boltSpeed: 60,
    gravity: 0,
    optic: "scope",
    magnification: 3.5,
    name: "Needle",
    role: "PRECISION",
    desc: "One powerful scoped shot, then reload.",
    damage: 170,
    interval: 0.5,
    magazine: 1,
    reserve: 12,
    reload: 2.4,
    spread: 0,
    pellets: 1,
    speed: 7.4,
    range: 60,
    color: 0x57c9df,
    size: 1.35,
    zoom: 27,
  },
  {
    id: "zipper",
    basedOn: "Whipper",
    reloadEmpty: 3.7666666666666666,
    ammoPickup: 40,
    automatic: true,
    spreadMax: 0.19,
    shotBloom: 0.045,
    spreadRecovery: 0.05,
    aimSpread: 0.6,
    movementSpread: 0.7,
    muzzle: 0.68,
    sightY: 0.285,
    boltSpeed: 37.5,
    gravity: 0,
    optic: "reflex",
    name: "Zipper",
    role: "RAPID",
    desc: "Move quickly and keep a stream of shots flying.",
    damage: 23,
    interval: 0.06666666666666667,
    magazine: 40,
    reserve: 200,
    reload: 3.1666666666666665,
    spread: 0.06,
    pellets: 1,
    speed: 7.4,
    range: 20,
    color: 0xb6db56,
    size: 0.78,
    zoom: 68,
  },
  {
    id: "thumper",
    basedOn: "RPEGG",
    reloadEmpty: 2.8333333333333335,
    ammoPickup: 1,
    automatic: false,
    spreadMax: 0.3,
    shotBloom: 0.3,
    spreadRecovery: 0.02,
    aimSpread: 0.5,
    movementSpread: 1,
    splashRadius: 2.75,
    minRange: 3,
    muzzle: 0.74,
    sightY: 0.285,
    boltSpeed: 12.0,
    gravity: 0,
    optic: "reflex",
    name: "Thumper",
    role: "LAUNCHER",
    desc: "A straight rocket that arms after three units of flight.",
    damage: 140,
    interval: 1.3333333333333333,
    magazine: 1,
    reserve: 3,
    reload: 2.8333333333333335,
    spread: 0.015,
    pellets: 1,
    speed: 7.4,
    range: 45,
    color: 0xcb8cec,
    size: 1.3,
    zoom: 65,
    projectile: true,
  },
  {
    id: "anchor",
    basedOn: "Free Ranger",
    reloadEmpty: 3.7666666666666666,
    ammoPickup: 15,
    automatic: false,
    spreadMax: 0.3,
    shotBloom: 0.3,
    spreadRecovery: 0.025,
    aimSpread: 0.5,
    movementSpread: 1,
    muzzle: 0.94,
    sightY: 0.285,
    boltSpeed: 52.5,
    gravity: 0,
    optic: "scope",
    magnification: 2.5,
    name: "Anchor",
    role: "MARKSMAN",
    desc: "A scoped semi-automatic rifle for deliberate follow-up shots.",
    damage: 105,
    interval: 0.43333333333333335,
    magazine: 15,
    reserve: 60,
    reload: 2.7666666666666666,
    spread: 0.004,
    pellets: 1,
    speed: 7.4,
    range: 50,
    color: 0x6dafcf,
    size: 1.3,
    zoom: 35,
  },
  {
    id: "duet",
    basedOn: "Tri-Hard",
    reloadEmpty: 3.433333333333333,
    ammoPickup: 24,
    automatic: false,
    spreadMax: 0.15,
    shotBloom: 0.037,
    spreadRecovery: 0.03,
    aimSpread: 0.6,
    movementSpread: 0.8,
    muzzle: 0.92,
    sightY: 0.285,
    boltSpeed: 45.0,
    gravity: 0,
    optic: "prism",
    magnification: 1.8,
    name: "Duet",
    role: "BURST",
    desc: "Three precise shots with each trigger press.",
    damage: 32,
    interval: 0.5,
    burst: 3,
    burstInterval: 0.1,
    magazine: 24,
    reserve: 150,
    reload: 2.6666666666666665,
    spread: 0.03,
    pellets: 1,
    speed: 7.4,
    range: 20,
    color: 0xf1d368,
    size: 0.95,
    zoom: 58,
  },
  {
    id: "pip",
    basedOn: "Cluck 9mm",
    reloadEmpty: 3.2666666666666666,
    ammoPickup: 15,
    automatic: false,
    spreadMax: 0.15,
    shotBloom: 0.09,
    spreadRecovery: 0.08,
    aimSpread: 0.8,
    movementSpread: 0.6,
    muzzle: 0.45,
    sightY: 0.22,
    boltSpeed: 30,
    gravity: 0,
    optic: "iron",
    name: "Pip",
    role: "SIDEARM",
    desc: "A dependable backup for every loadout.",
    damage: 26,
    interval: 0.13333333333333333,
    magazine: 15,
    reserve: 60,
    reload: 2.6666666666666665,
    spread: 0.035,
    pellets: 1,
    speed: 7.4,
    range: 15,
    color: 0xf2e5ba,
    size: 0.6,
    zoom: 65,
    secondary: true,
  },
];
// Maximum flight distance is separate from the balance/effective-range stat.
// Full swept collision remains active until the projectile reaches this limit.
for(const w of WEAPONS) w.flightRange=w.projectile?180:w.pellets>1?65:w.optic==='scope'?600:320;
export const ROYALE_WEAPONS = [
 {...WEAPONS[2],id:'peeper',name:'Peeper',role:'MARKSMAN',desc:'A repeating long-range shell scout.',damage:68,magazine:8,reserve:60,interval:.36,reload:2.2,reloadEmpty:2.5,spread:.008,range:110,optic:'scope',magnification:2.5,color:0x94de9a},
 {...WEAPONS[1],id:'doubleyolk',name:'Double Yolk',role:'TACTICAL',desc:'A quick cycling tactical scatter blaster.',damage:7,pellets:10,magazine:6,reserve:48,interval:.5,reload:2.4,reloadEmpty:2.7,range:22,color:0xec99c5},
 {...WEAPONS[0],id:'comet',name:'Comet',role:'ENERGY',desc:'A precise energy carbine with luminous rounds.',damage:27,magazine:24,reserve:240,interval:.14,reload:2.1,reloadEmpty:2.4,spread:.013,range:95,color:0x8bafff},
];
for(const w of [...WEAPONS,...ROYALE_WEAPONS])if(OPTICS[w.id]){w.ads={...OPTICS[w.id]};w.magnification=w.ads.magnification;w.sightY=w.ads.radius+.15;}
const royaleStats = new Map();
export const MODES = [
 {id:"royale",name:"Yolk Royale",short:"ROYALE",description:"Drop in, loot up, outrun the storm. Last egg standing.",limit:1,teams:false},
  {
    id: "ffa",
    name: "Free for all",
    short: "FFA",
    description: "Every egg for itself. First to 20 eliminations.",
    limit: 20,
    teams: false,
  },
  {
    id: "teams",
    name: "Team scramble",
    short: "TEAMS",
    description: "Coral versus blue. First team to 35 eliminations.",
    limit: 35,
    teams: true,
  },

];
export const COLORS = [
  "#fff6da",
  "#f9b74a",
  "#72cfdd",
  "#ee897b",
  "#a5d76e",
  "#b7a1ec",
  "#8492a6",
  "#fae8b6",
  "#ffffff", "#273345", "#ff637e", "#d94949", "#f78336", "#ffe45e",
  "#45b979", "#21796d", "#80eacb", "#3d8ce8", "#464eb3", "#8c54c9",
  "#efb4df", "#bd728b", "#946344", "#b9ccd4",
];
export const HATS = ["No headwear", "Headphones", "Cap", "Crown", "Sprout", "Top hat", "Beanie", "Wizard", "Cowboy", "Party hat", "Halo", "Bunny ears", "Cat ears", "Chef", "Beret", "Antenna", "Flower", "Viking", "Pirate", "Propeller"];
export const PATTERNS = ["No pattern", "Stripes", "Polka dots", "Checkerboard", "Confetti", "Lightning", "Stars", "Two tone", "Waves", "Diamond"];
export const FINISHES = ["Classic", "Matte", "Gloss", "Metallic"];
export const EYEWEAR = ["Classic visor", "Round goggles", "Sunglasses", "Cyclops", "Square glasses", "Star shades", "No eyewear"];
// Append the plain option so existing saved eyewear IDs keep their meaning.
export const NO_EYEWEAR = 6;
const cosmeticIndex = (value, options) => Number.isInteger(Number(value)) && Number(value) >= 0 && Number(value) < options.length ? Number(value) : 0;
export const TEAM_COLORS = [0x3d8ce8, 0xd94949];
export const clamp = (n, a, b) => Math.max(a, Math.min(b, n));
export const weapon = (id) => WEAPONS.find((w) => w.id === id) || ROYALE_WEAPONS.find(w => w.id === id) || WEAPONS[0];
export const gun = (p) => {
 if (!p.inventory) return weapon(p.slot === 1 ? "pip" : p.weapon);
 const item=p.inventory[p.slot], base=weapon(item?.weapon ? item.id : 'pip');
 const rarity=Math.max(0,Math.min(4,item?.rarity||0)),key=base.id+rarity;
 if(!royaleStats.has(key)) royaleStats.set(key,{...base,damage:base.damage*.72*(1+rarity*.06),range:Math.max(base.range,base.id==='scatter'||base.id==='doubleyolk'?25:base.id==='thumper'?130:140),boltSpeed:base.boltSpeed,reload:base.reload*(1-rarity*.035),reloadEmpty:base.reloadEmpty*(1-rarity*.035)});
 return royaleStats.get(key);
};
export const mode = (id) => MODES.find((m) => m.id === id) || MODES.find(m => m.id === "ffa");
export const cleanName = safeName;
export function safeProfile(p = {}) {
  if (!p || typeof p !== 'object') p = {};
  return {
    name: cleanName(p.name),
    weapon: WEAPONS.some(w => w.id === p.weapon && !w.secondary) ? p.weapon : "sprinter",
    color: COLORS.includes(p.color) ? p.color : COLORS[0],
    hat: cosmeticIndex(p.hat, HATS),
    pattern: cosmeticIndex(p.pattern, PATTERNS),
    finish: cosmeticIndex(p.finish, FINISHES),
    eyewear: p.eyewear == null ? NO_EYEWEAR : cosmeticIndex(p.eyewear, EYEWEAR),
    accent: COLORS.includes(p.accent) ? p.accent : COLORS[1],
    ...cosmeticProfile(p),
  };
}
export function rng(seed) {
  let s = seed >>> 0;
  const random = () => {
    s += 0x6d2b79f5;
    let t = Math.imul(s ^ (s >>> 15), 1 | s);
    t ^= t + Math.imul(t ^ (t >>> 7), 61 | t);
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
  random.state = () => s;
  random.restore = value => { s = value >>> 0; };
  return random;
}

export const nameKey = value => String(value ?? '').normalize('NFKC').toLowerCase().replace(/\s+/g,' ').trim();
export function randomAppearance(random = Math.random) {
 const pick = list => list[Math.floor(random() * list.length)];
 return {color:pick(COLORS),accent:pick(COLORS),hat:Math.floor(random()*HATS.length),pattern:Math.floor(random()*PATTERNS.length),finish:Math.floor(random()*FINISHES.length),eyewear:Math.floor(random()*EYEWEAR.length)};
}
export const BOT_DIFFICULTIES = ['Casual','Intermediate','Advanced','Impossible'];
