import {RELEASE} from './releases.js';
import {eggsMarkup} from './currency-ui.js';
export const html=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const EXPERIENCES=[
 {id:'solo',mode:'royale',teamSize:1,name:'Yolk Royale',tag:'SOLO',symbol:'◈',description:'One egg. One chance. Loot, build and outlast the storm.',detail:'32 contestants · One life',art:'sunrise'},
 {id:'duos',mode:'royale',teamSize:2,name:'Yolk Royale',tag:'DUOS',symbol:'◈ ◈',description:'Drop together. Watch each other’s shell. Last Duo wins.',detail:'Teams of 2 · Fill / No Fill',art:'orchard'},
 {id:'ffa',mode:'ffa',teamSize:1,name:'Free For All',tag:'ARENA',symbol:'◎',description:'Choose your blaster. Every other egg is a rival.',detail:'8 players · Respawns',art:'coral'},
 {id:'teams',mode:'teams',teamSize:1,name:'Team Scramble',tag:'ARENA',symbol:'◆ ◆',description:'Blue or coral. Work together to win the scramble.',detail:'8 players · Two teams',art:'twilight'},
];
export const selectedExperience=s=>EXPERIENCES.find(e=>e.mode===s?.mode&&e.teamSize===(s.teamSize||1))||EXPERIENCES[0];
export function lobbyMarkup({profile,party,id,online,balance}){
 const e=selectedExperience(party?.selection),leader=!party||party.leader===id,queued=party?.state==='queueing',members=party?.members||[{id,profile,ready:true}],me=members.find(m=>m.id===id),two=members.length>1;
 return `<div class="yard-lobby-backdrop" aria-hidden="true"><div class="yard-sun"></div></div><header class="yard-nav"><a class="yard-logo" href="#" data-action="lobby-home" aria-label="Yolk Yard home">YOLK<span>YARD</span></a><nav aria-label="Main navigation"><button class="active" data-action="lobby-home">PLAY</button><button data-action="locker">LOCKER</button><button data-action="item-shop">ITEM SHOP</button><button data-action="career">CAREER</button></nav><div class="yard-nav-tools"><button class="yard-wallet" data-action="item-shop">${eggsMarkup(balance)}</button><button data-action="social" aria-label="Social and party">♟ <span>SOCIAL</span>${two?'<i>2</i>':''}</button><button data-action="settings" aria-label="Settings">⚙</button></div></header>
 <section class="yard-season"><span class="eyebrow">GOOD EGGS. GREAT COMPANY.</span><h1>Better<br>together.</h1><button data-action="updates">QUALITY UPDATE ${RELEASE} <span>↗</span></button></section>
 <section class="yard-party" aria-label="Your party"><div class="yard-section-label">YOUR PARTY <span>${members.length} / 2</span></div>${members.map(m=>`<div class="yard-member"><i class="yard-egg-icon" style="--shell:${html(m.profile.color)}"></i><div><strong>${html(m.profile.name)} ${m.id===party?.leader?'♛':''}</strong><small>${m.id===id?'YOU · ':''}${queued?'MATCHMAKING':m.inMatch?'IN A MATCH':m.connected===false?'RECONNECTING':m.ready||m.id===party?.leader?'READY':'NOT READY'}</small></div></div>`).join('')}${!two?'<button class="yard-invite" data-action="social"><b>＋</b> Invite a teammate</button>':''}<button class="yard-party-link" data-action="social">${party?.privacy==='open'?'OPEN PARTY':'INVITE ONLY'} · MANAGE</button></section>
 <div class="yard-character-label"><span>${two?'THE PARTY IS HERE':'READY TO HATCH'}</span><strong>${html(profile.name)}</strong><button data-action="locker">EDIT YOUR LOOK ↗</button></div>
 <section class="yard-play-card" aria-label="Play"><button class="yard-selected-mode ${e.art}" data-action="play" ${!leader||queued?'disabled':''}><span class="eyebrow">${e.tag} <span>CHANGE ↗</span></span><strong>${e.name}</strong><small>${e.detail}</small></button>${e.id==='duos'?`<div class="yard-fill" role="group" aria-label="Duo teammate fill"><button data-action="duo-fill" aria-pressed="${party?.selection.duoFill!==false}" ${!leader||queued||two?'disabled':''}>FILL</button><button data-action="duo-no-fill" aria-pressed="${party?.selection.duoFill===false}" ${!leader||queued||two?'disabled':''}>NO FILL</button><small>${two?'Your party is your Duo':party?.selection.duoFill===false?'Enter as a solo Duo':'Find a teammate'}</small></div>`:''}
 ${e.mode!=='royale'?'<button class="yard-custom" data-action="loadout">CHOOSE LOADOUT <span>›</span></button>':''}<div class="yard-queue-state" role="status">${queued?'Finding a match for your party…':!online?'Connecting to party service…':party?.state==='playing'?'Waiting for your party to return to the lobby':!leader?'Your leader selects the match':two&&!members.every(m=>m.ready||m.id===party.leader)?'Waiting for your teammate to ready up':e.id==='duos'?'Drop in. Team up. Stay sunny.':'Your next scramble starts here.'}</div>
 <button class="primary yard-find" data-action="${queued?'party-cancel':leader?'find-public':'party-ready'}" ${!online||party?.state==='playing'||queued&&!leader?'disabled':''}>${queued?'CANCEL MATCHMAKING':leader?'FIND PUBLIC MATCH':me?.ready?'UNREADY':'READY UP'} <span>▶</span></button>${!queued&&leader?'<button class="yard-custom" data-action="play-custom">CUSTOM MATCH <span>›</span></button>':''}</section>
 <footer class="yard-footer"><button data-action="profile">${html(profile.name)} · PLAYER DETAILS</button><button data-action="help">HOW TO PLAY</button><button data-action="about">ABOUT & CREDITS</button></footer>`;
}
export function modeMarkup(selection,locked=false){return `<p>Pick your next scramble. Your party follows the leader’s selection.</p><div class="yard-mode-grid">${EXPERIENCES.map(e=>`<button class="yard-mode-card ${e.art}" data-experience="${e.id}" aria-pressed="${selectedExperience(selection).id===e.id}" ${locked?'disabled':''}><span class="yard-mode-art" aria-hidden="true">${e.symbol}</span><span class="eyebrow">${e.tag}</span><strong>${e.name}</strong><p>${e.description}</p><small>${e.detail}</small></button>`).join('')}</div>`;}
export function socialMarkup(party,id,players){const leader=party.leader===id;return `<div class="yard-social"><section><h3>YOUR PARTY</h3><p>${party.privacy==='open'?'Online players can join your open party.':'Only invited players can join.'}</p>${party.members.map(m=>`<div class="social-person"><div><strong>${html(m.profile.name)} ${m.id===party.leader?'♛':''}</strong><small>${m.inMatch?'In a match':m.connected?'Online':'Reconnecting'}${m.ready?' · Ready':''}</small></div>${leader&&m.id!==id?`<button data-party-kick="${m.id}">Remove</button>`:''}</div>`).join('')}<div class="split-actions">${leader?`<button data-action="party-privacy">${party.privacy==='open'?'MAKE INVITE ONLY':'OPEN PARTY'}</button>`:''}${party.members.length>1?'<button data-action="party-leave">LEAVE PARTY</button>':''}</div></section><section><div class="yard-section-label">ONLINE IN YOLK YARD <button data-action="social">↻ Refresh</button></div><p class="hint">Players connected right now. Nicknames belong to browser sessions.</p>${players.filter(p=>!party.members.some(m=>m.id===p.id)).map(p=>`<div class="social-person"><div><strong>${html(p.name)}</strong><small>${p.state==='idle'?'In lobby':p.state==='queueing'?'Matchmaking':'In a match'}</small></div>${leader&&party.members.length<2?`<button data-party-invite="${p.id}">INVITE</button>`:''}${p.joinable&&p.state==='idle'?`<button data-party-join="${p.party}">JOIN</button>`:''}</div>`).join('')||'<p class="social-empty">No other players online yet. You can still find a public match with bot fill.</p>'}</section></div>`;}
