import {RELEASE} from './releases.js';
import {eggsMarkup} from './currency-ui.js';
export const html=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export const EXPERIENCES=[
 {id:'solo',mode:'royale',teamSize:1,name:'Frontier Royale',tag:'SOLO',symbol:'◈',description:'One operator. One chance. Loot, build and outlast the storm.',detail:'32 contestants · One life',art:'sunrise'},
 {id:'duos',mode:'royale',teamSize:2,name:'Frontier Royale',tag:'DUOS',symbol:'◈ ◈',description:'Drop together. Watch each other’s back. Last Duo wins.',detail:'Teams of 2 · Fill / No Fill',art:'orchard'},
 {id:'squads',mode:'royale',teamSize:4,name:'Frontier Royale',tag:'SQUADS',symbol:'◈ ◈ ◈ ◈',description:'Four operators. One squad. Revive, regroup and hold the frontier.',detail:'Teams of 4 · Fill / No Fill',art:'twilight'},
 {id:'ffa',mode:'ffa',teamSize:1,name:'Free For All',tag:'ARENA',symbol:'◎',description:'Choose your blaster. Every other operator is a rival.',detail:'8 players · Respawns',art:'coral'},
];
export const selectedExperience=s=>EXPERIENCES.find(e=>e.mode===s?.mode&&e.teamSize===(s.teamSize||1))||EXPERIENCES[0];
export function lobbyNavigation({profile,party,id,balance,section='play'}){const members=party?.members||[{id,profile}],two=members.length>1;return `<div class="yard-lobby-backdrop" aria-hidden="true"><div class="yard-sun"></div></div><header class="yard-nav"><a class="yard-logo" href="#" data-action="lobby-home" aria-label="Ravelfront home">RAVEL<span>FRONT</span></a><nav aria-label="Main navigation"><button class="${section==='play'?'active':''}" aria-current="${section==='play'?'page':'false'}" data-action="lobby-home">PLAY</button><button class="${section==='locker'?'active':''}" aria-current="${section==='locker'?'page':'false'}" data-action="locker">LOCKER</button><button class="${section==='shop'?'active':''}" aria-current="${section==='shop'?'page':'false'}" data-action="item-shop">ITEM SHOP</button><button class="${section==='career'?'active':''}" aria-current="${section==='career'?'page':'false'}" data-action="career">CAREER</button></nav><div class="yard-nav-tools"><button class="yard-wallet" data-action="item-shop">${eggsMarkup(balance)}</button><button data-action="social" aria-label="Social and party">♟ <span>SOCIAL</span>${two?'<i>'+members.length+'</i>':''}</button><button data-action="settings" aria-label="Settings">⚙ <span>SETTINGS</span></button></div></header>`;}
export function publicRoyaleMarkup({publicMatch:m,publicMatchElapsed=0,party,id,online}){
 const seconds=n=>`${Math.floor(Math.max(0,n)/60)}:${String(Math.max(0,n)%60).padStart(2,'0')}`;
 const elapsed=Math.floor(publicMatchElapsed/1000),countdown=Math.max(0,(m?.countdownSeconds||0)-elapsed),leader=!party||party.leader===id;
 const ready=party?.members.every(p=>p.id===party.leader||p.ready)??true;
 const available=!!m&&online&&publicMatchElapsed<5000,joining=m?.joinable&&countdown>0,full=(joining?m?.availableSeats:m?.availableSpectators)<(party?.members.length||1);
 const disabled=!available||!leader||!ready||party?.state!=='idle'||full||m?.joinable&&!countdown;
 const phase=!available?'Connecting to public match…':m.phase==='results'?`Next Spawn Island in ${Math.max(0,m.restartSeconds-elapsed)}s`:joining?`SPAWN ISLAND · ${countdown}s to departure`:m.stage==='battle-bus'?'BATTLE BUS · ROUND IN PROGRESS':'ROUND IN PROGRESS';
 return `<div class="public-royale-heading"><span class="eyebrow">ONE RECURRING PUBLIC MATCH</span><span class="public-royale-live">${available?'● LIVE':'● CONNECTING'}</span></div><div class="public-royale-title"><strong>FRONTIER ROYALE</strong><small>SOLO · INTERMEDIATE BOTS · 48 CONTESTANTS</small></div><div class="public-royale-facts"><span class="public-royale-humans"><b>${m?.humanPlayers??'–'}</b> REAL PLAYERS / 48</span><span>${available?`${m.phase==='results'?'Next round':'Est. remaining'} · ${m.phase==='results'?'': '~'}${seconds(Math.max(0,m.estimatedSeconds-elapsed))}`:'Estimated time connecting…'}</span></div><div class="public-royale-action"><span role="status">${phase}</span><button class="primary" data-action="${joining?'public-join':'public-spectate'}" ${disabled?'disabled':''}>${joining?'JOIN':'SPECTATE'} <span>▶</span></button></div><p class="public-royale-hint">${!leader?'Ready up below; your leader joins for the party.':!ready?'Waiting for party members to ready up.':full?'All seats are occupied. Try again shortly.':joining?'Joining replaces a bot. Departure waits for a real player.':'Spectate now; enter next Spawn Island if a seat is available.'}</p>`;
}
export function lobbyMarkup({profile,party,id,online,balance,publicMatch,publicMatchElapsed}){
 const e=selectedExperience(party?.selection),leader=!party||party.leader===id,queued=party?.state==='queueing',members=party?.members||[{id,profile,ready:true}],me=members.find(m=>m.id===id),two=members.length>1;
 return `${lobbyNavigation({profile,party,id,balance})}
 <section class="public-royale-card" aria-label="Recurring public Royale">${publicRoyaleMarkup({publicMatch,publicMatchElapsed,party,id,online})}</section>
 <section class="yard-season"><span class="eyebrow">SEASON ZERO / THE RELAY WAR</span><h1>HOLD THE<br>FRONTIER.</h1><button data-action="updates">QUALITY UPDATE ${RELEASE} <span>↗</span></button></section>
 <section class="yard-party" data-count="${members.length}" aria-label="Your party"><div class="yard-section-label">YOUR PARTY <span>${members.length} / 4</span></div>${members.map(m=>`<div class="yard-member"><i class="operator-insignia" aria-hidden="true">R</i><div><strong>${html(m.profile.name)} ${m.id===party?.leader?'♛':''}</strong><small>${m.id===id?'YOU · ':''}${queued?'CONNECTING':m.inMatch?'IN A MATCH':m.connected===false?'RECONNECTING':m.ready||m.id===party?.leader?'READY':'NOT READY'}</small></div></div>`).join('')}${!leader?`<button class="primary yard-ready" data-action="party-ready" ${queued||party?.state==='playing'?'disabled':''}>${me?.ready?'UNREADY':'READY UP'}</button>`:''}${members.length<4?'<button class="yard-invite" data-action="social"><b>＋</b> Invite players</button>':''}<button class="yard-party-link" data-action="social">${party?.privacy==='open'?'OPEN PARTY':'INVITE ONLY'} · MANAGE</button></section>
 <div class="yard-character-label"><span>${two?'THE PARTY IS HERE':'OPERATOR READY'}</span><strong>${html(profile.name)}</strong><button data-action="locker">EDIT YOUR LOOK ↗</button></div>
 <section class="yard-play-card yard-private-card" aria-label="Private matches"><span class="eyebrow">YOUR RULES · YOUR PARTY</span><p>Free For All or Frontier Royale<br>Player-hosted · Room code · Manual start</p><button class="primary yard-find" data-action="play-custom" ${!online||!leader||queued||party?.state==='playing'?'disabled':''}>CUSTOM PRIVATE MATCH <span>▶</span></button></section>
 <footer class="yard-footer"><button data-action="connection-report">CONNECTION REPORT</button><button data-action="profile">${html(profile.name)} · PLAYER DETAILS</button><button data-action="help">HOW TO PLAY</button><button data-action="about">ABOUT & CREDITS</button></footer>`;
}
export function modeMarkup(selection,locked=false){return `<p>Choose your next deployment. Your party follows the leader’s selection.</p><div class="yard-mode-grid">${EXPERIENCES.map(e=>`<button class="yard-mode-card ${e.art}" data-experience="${e.id}" aria-pressed="${selectedExperience(selection).id===e.id}" ${locked?'disabled':''}><span class="yard-mode-art" aria-hidden="true">${e.symbol}</span><span class="eyebrow">${e.tag}</span><strong>${e.name}</strong><p>${e.description}</p><small>${e.detail}</small></button>`).join('')}</div>`;}
export const presenceLabel=s=>({'offline':'Offline','online':'Online','lobby':'In Lobby','in-party':'In Party','matchmaking':'Matchmaking','in-match':'In Match','spectating':'Spectating'}[s]||'Offline');
export function socialMarkup(party,id,model,tab='friends'){
 const leader=party.leader===id,idle=party.state==='idle',canWatch=!party.members.find(m=>m.id===id)?.inMatch&&party.state!=='queueing',players=tab==='online'?model.online:model.friends;
 const action=(type,id,text)=>`<button data-social-action="${type}" data-player-id="${html(id)}">${text}</button>`;
 const person=p=>`<article class="social-person"><div><strong>${html(p.name)}</strong><small class="presence ${p.presence==='offline'?'offline':'active'}">${presenceLabel(p.presence)}</small></div><div class="social-actions">${!party.members.some(m=>m.id===p.id)&&idle&&party.members.length<4&&p.inviteable?`<button data-party-invite="${p.id}">Invite to Party</button>`:''}${p.joinable&&idle?`<button data-party-join="${p.party}">Join Party</button>`:''}${p.spectatable&&canWatch?`<button data-spectate-friend="${html(p.id)}">Spectate Friend</button>`:''}${p.relationship==='friends'?action('friend-remove',p.id,'Remove Friend'):p.relationship==='none'?action('friend-send',p.id,'Add Friend'):p.relationship==='incoming'?action('friend-accept',p.id,'Accept Friend'):p.relationship==='outgoing'?'<span class="social-pending">Request sent</span>':''}${action('block',p.id,'Block')}</div></article>`;
 return `<div class="yard-social"><section class="social-party"><h3>YOUR PARTY <small>${party.members.length} / 4</small></h3><p>${party.privacy==='open'?'Online players may join your open party.':'Players need an invitation to join.'}</p>${party.members.map((m,i)=>`<div class="social-person"><span class="social-slot">${i+1}</span><div><strong>${html(m.profile.name)} ${m.id===party.leader?'♛ LEADER':''}</strong><small>${m.connected?presenceLabel(m.presence):'Reconnecting…'}${m.ready?' · Ready':''}</small></div>${leader&&party.state!=='playing'&&m.id!==id?`<button data-party-kick="${m.id}">Remove From Party</button>`:''}</div>`).join('')}<div class="split-actions">${leader&&idle?`<button data-action="party-privacy">${party.privacy==='open'?'MAKE INVITE ONLY':'OPEN PARTY'}</button>`:''}${party.members.length>1?'<button data-action="party-leave">LEAVE PARTY</button>':''}</div></section>
 <section class="social-browser"><div class="friend-code"><div><small>YOUR FRIEND CODE</small><strong>${html(model.self.code)}</strong></div><button data-action="copy-friend-code">COPY CODE</button></div><div class="social-toolbar"><button class="primary" data-action="add-friend">+ ADD FRIEND</button><button data-action="social">↻ Refresh</button></div><nav class="social-tabs" aria-label="Social browsing"><button data-social-tab="friends" aria-pressed="${tab==='friends'}">FRIENDS (${model.friends.length})</button><button data-social-tab="online" aria-pressed="${tab==='online'}">OTHERS ONLINE (${model.total})</button></nav>
 ${model.invitations.length?`<section class="social-requests"><h3>PARTY INVITATIONS</h3>${model.invitations.map(i=>`<div class="social-person"><div><strong>${html(i.name)}</strong><small>Party ${i.size} / 4 · expires in ${Math.max(0,Math.ceil((i.expires-Date.now())/1000))}s</small></div><button data-party-accept="${i.id}">Accept</button><button data-party-decline="${i.id}">Decline</button></div>`).join('')}</section>`:''}
 ${model.requests.length?`<section class="social-requests"><h3>FRIEND REQUESTS</h3>${model.requests.map(r=>`<div class="social-person"><div><strong>${html(r.player?.name||'Player')}</strong><small>${r.direction==='incoming'?'Incoming request':'Outgoing request'}</small></div>${r.direction==='incoming'?action('friend-accept',r.from,'Accept')+action('friend-decline',r.from,'Decline'):action('friend-cancel',r.to,'Cancel')}</div>`).join('')}</section>`:''}
 <div class="social-list">${players.map(person).join('')||`<p class="social-empty">${tab==='friends'?'No friends yet. Add someone using their Friend Code.':'No other eligible players online.'}</p>`}</div>${tab==='online'&&model.total>25?`<div class="split-actions"><button data-social-page="${Math.max(0,model.offset-25)}" ${model.offset===0?'disabled':''}>Previous</button><small>${model.offset+1}–${Math.min(model.offset+25,model.total)} / ${model.total}</small><button data-social-page="${model.offset+25}" ${model.offset+25>=model.total?'disabled':''}>Next</button></div>`:''}
 ${model.blocked.length?`<details class="social-blocked"><summary>Blocked players (${model.blocked.length})</summary>${model.blocked.map(p=>`<div class="social-person"><strong>${html(p.name)}</strong>${action('unblock',p.id,'Unblock')}</div>`).join('')}</details>`:''}<p class="hint">Your identity and friends stay with this browser. Clearing site data creates a new identity. Friend Codes only find players.</p></section></div>`;
}
