import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {TransformControls} from 'three/addons/controls/TransformControls.js';
import {BASE_MAPS,baseMap} from './maps.js';
import {MAP_PREFABS,prefab,baseObjects,sourceRecord,compileLayout,validateLayout,layoutKey} from './map-layout.js';
import {MapDocument} from './map-document.js';
import {buildIslandSteps} from './royale-view.js';
import {buildArena} from './arenas.js';
import {makeMapObject,disposeMapGroup,parseModel,registerModel} from './map-object-view.js';
import {worldKit} from './view.js';
import {groundAt} from './terrain.js';
import {rayBox,movePlayer,canStand,EYE} from './physics.js';
import './map-editor.css';

const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icon=p=>({Structure:'▧',Equipment:'◈',Vehicles:'▰',Nature:'♠',Details:'◇',Gameplay:'◎',Models:'⬡'}[p.category]||'◇');
const clone=v=>structuredClone(v);
const number=n=>Math.round(n*1000)/1000;
const uuid=()=>crypto.randomUUID().replaceAll('-','');
const autosaveKey=id=>'ravelfront-map-draft-v1:'+id;

export class MapEditor{
 constructor({owner,overview,onClose}){this.owner=owner;this.overview=overview;this.onClose=onClose;this.assets=overview.assets||[];this.selected=null;this.placing=null;this.tab='catalog';this.search='';this.mode='translate';this.snap=1;this.rotationSnap=15;this.gridVisible=true;this.locked=new Set();this.keys=new Set();this.closed=false;this.busy=false;this.listeners=[];this.buildGeneration=0;this.tickAt=performance.now();}
 async open(){
  this.root=document.createElement('section');this.root.id='map-editor';this.root.tabIndex=-1;this.root.setAttribute('aria-label','Owner map editor');
  this.root.innerHTML=`<header class="map-topbar"><div class="map-wordmark"><b>RAVELFRONT</b><span>OWNER / MAP EDITOR</span></div><label class="map-map-picker">EDIT MAP<select id="map-picker">${BASE_MAPS.map(m=>`<option value="${m.id}">${escape(m.name)}</option>`).join('')}</select></label><div class="map-toolbar-actions"><span class="map-save-state" id="map-save-state">Loading draft…</span><button data-editor-action="undo" title="Undo (Ctrl/⌘ Z)">↶ Undo</button><button data-editor-action="redo" title="Redo (Ctrl/⌘ Shift Z)">↷ Redo</button><button data-editor-action="walk">Test walk</button><button data-editor-action="export">Export</button><button data-editor-action="import">Import map</button><button data-editor-action="save">Save draft</button><button class="primary" data-editor-action="publish">Publish map</button><button data-editor-action="close">Exit</button></div></header><div class="map-layout"><aside class="map-sidebar"><div class="map-panel-top"><div class="map-tabs"><button class="active" data-editor-tab="catalog">Objects</button><button data-editor-tab="scene">Scene</button></div><input id="map-search" type="search" placeholder="Search objects…" aria-label="Search objects"><button data-editor-action="model">Import GLB model</button></div><div id="map-local-recovery"></div><div class="map-scroll" id="map-catalog"></div></aside><div class="map-viewport"><canvas aria-label="Editable 3D map" tabindex="0"></canvas><div class="map-view-tools"><button data-editor-action="mode-translate" class="active" title="Move (W)">Move</button><button data-editor-action="mode-rotate" title="Rotate (E)">Rotate</button><button data-editor-action="mode-scale" title="Resize (R)">Resize</button><button data-editor-action="focus" title="Focus selected (F)">Focus</button><button data-editor-action="top">Top view</button><button data-editor-action="grid" class="active">Grid</button><button data-editor-action="snap">Snap: 1m</button></div><div class="map-view-help" id="map-help">Click to select · Drag colored handles to edit<br>Right drag: orbit · Middle drag: pan · Scroll: zoom</div><div class="map-view-label" id="map-view-label"></div><div class="map-loading" id="map-loading">Loading map…</div><div class="map-walk-reticle" hidden></div></div><aside class="map-sidebar map-inspector"><div class="map-panel-top"><h3>Object properties</h3></div><div id="map-inspector" class="map-inspector-body"><p class="map-empty">Select an object in the map or Scene list.</p></div></aside></div><footer class="map-footer"><span id="map-status" role="status" aria-live="polite">Loading your map draft…</span><span id="map-count"></span><span class="map-shortcuts">W / E / R · F focus · Ctrl/⌘ D duplicate · Delete</span></footer><input hidden type="file" id="map-import-file" accept=".json,application/json"><input hidden type="file" id="map-model-file" accept=".glb,model/gltf-binary">`;
  document.body.append(this.root);this.canvas=this.$('canvas');
  try{this.renderer=new THREE.WebGLRenderer({canvas:this.canvas,antialias:true});}catch(error){this.root.remove();throw error;}
  this.renderer.setPixelRatio(Math.min(devicePixelRatio||1,1.25));this.renderer.outputColorSpace=THREE.SRGBColorSpace;
  this.scene=new THREE.Scene();this.camera=new THREE.PerspectiveCamera(55,1,.08,1600);this.scene.add(new THREE.HemisphereLight(0xebfaff,0x536450,2.5));const sun=new THREE.DirectionalLight(0xfff0d9,2.2);sun.position.set(-80,180,65);this.scene.add(sun);
  this.world=new THREE.Group();this.scene.add(this.world);this.markerRoot=new THREE.Group();this.scene.add(this.markerRoot);
  this.controls=new OrbitControls(this.camera,this.canvas);this.controls.enableDamping=true;this.controls.dampingFactor=.12;this.controls.maxDistance=850;this.controls.minDistance=1;this.controls.maxPolarAngle=Math.PI*.49;this.controls.mouseButtons={LEFT:null,MIDDLE:THREE.MOUSE.PAN,RIGHT:THREE.MOUSE.ROTATE};
  this.transform=new TransformControls(this.camera,this.canvas);this.transform.setSize(.9);this.scene.add(this.transform.getHelper());
  this.transform.addEventListener('dragging-changed',e=>{this.controls.enabled=!e.value;this.dragging=e.value;if(e.value)this.dragBefore=clone(this.doc.record(this.selected));else if(this.dragBefore){const r=this.readTransform();if(r){this.commit(r);void this.rebuild();}this.dragBefore=null;}});
  this.transform.addEventListener('objectChange',()=>this.updateTransformFields());
  this.raycaster=new THREE.Raycaster();this.pointer=new THREE.Vector2();this.resizeObserver=new ResizeObserver(()=>this.resize());this.resizeObserver.observe(this.$('.map-viewport'));
  this.listen(this.root,'click',e=>this.click(e));this.listen(this.root,'change',e=>this.change(e));this.listen(this.$('#map-search'),'input',e=>{this.search=e.target.value;this.renderCatalog();});
  this.listen(this.canvas,'pointerdown',e=>{if(e.button===0)this.pointerDown={x:e.clientX,y:e.clientY,at:performance.now(),dragged:this.dragging};});
  this.listen(this.canvas,'pointerup',e=>{if(e.button!==0||!this.pointerDown||this.walking)return;const p=this.pointerDown;this.pointerDown=null;if(p.dragged||this.dragging||this.transform.axis||Math.hypot(e.clientX-p.x,e.clientY-p.y)>5)return;if(this.placing)this.placeAt(e);else this.pick(e);});
  this.listen(this.canvas,'pointermove',e=>{if(this.dragging&&this.pointerDown)this.pointerDown.dragged=true;if(this.walking&&document.pointerLockElement===this.canvas){this.walkPlayer.yaw-=e.movementX*.002;this.walkPlayer.pitch=Math.max(-1.4,Math.min(1.4,this.walkPlayer.pitch-e.movementY*.002));}else if(this.placing&&performance.now()-(this.ghostAt||0)>40){this.ghostAt=performance.now();this.moveGhost(this.pointAt(e));}});
  this.listen(this.canvas,'contextmenu',e=>e.preventDefault());this.listen(window,'keydown',e=>this.key(e),true);this.listen(window,'keyup',e=>this.keys.delete(e.code),true);this.listen(window,'blur',()=>this.keys.clear());
  this.listen(document,'pointerlockchange',()=>{if(this.walking&&document.pointerLockElement!==this.canvas)this.endWalk();});
  this.listen(window,'beforeunload',e=>{if(this.doc?.dirty){e.preventDefault();e.returnValue='';}});
  this.resize();this.frame=now=>{if(this.closed)return;const dt=Math.min(.05,(now-this.tickAt)/1000);this.tickAt=now;if(this.walking)this.walk(dt);else this.controls.update();this.world.userData.details?.update({x:this.controls.target.x,y:this.controls.target.y,z:this.controls.target.z},{quality:'low',time:now/1000});this.renderer.render(this.scene,this.camera);this.raf=requestAnimationFrame(this.frame);};this.raf=requestAnimationFrame(this.frame);
  await this.loadMap('sunnybreak');this.root.focus();return this;
 }
 $(s){return this.root.querySelector(s);}
 listen(el,type,handler,options){el.addEventListener(type,handler,options);this.listeners.push(()=>el.removeEventListener(type,handler,options));}
 resize(){const rect=this.$('.map-viewport').getBoundingClientRect();if(!rect.width||!rect.height)return;this.renderer.setSize(rect.width,rect.height,false);this.camera.aspect=rect.width/rect.height;this.camera.updateProjectionMatrix();}
 async api(action,data={}){if(!this.owner.token||this.owner.expires<=Date.now())throw Object.assign(Error('Owner access expired. Unlock to save or publish; your edits are still here.'),{status:401});return this.owner.request('/maps',{method:'POST',body:JSON.stringify({token:this.owner.token,action,...data})});}
 async loadMap(id){
  this.flushLocal();
  this.busy=true;this.updateButtons();this.$('#map-loading').hidden=false;this.$('#map-loading').textContent='Loading your saved draft…';
  try{const data=await this.api('get',{mapId:id});if(this.closed)return;this.mapId=id;this.base=baseMap(id);this.objectSources=new Map();for(const source of baseObjects(this.base))for(const b of source.boxes)this.objectSources.set(b.objectId||'world-'+(this.base.authored||this.base.boxes).indexOf(b),source.id);this.assets=data.assets||this.assets;this.version=data.draftVersion;this.publishedRevision=data.revision;this.publishedLayout=data.published;this.doc=new MapDocument(this.base,data.draft);this.selected=null;this.search='';this.$('#map-search').value='';this.$('#map-picker').value=id;this.locked.clear();this.cancelPlacement();this.transform.detach();this.renderCatalog();this.renderInspector();this.localRecovery();this.resetCamera();await this.rebuild();this.status('Draft loaded. Publishing applies it to new rounds.');if(!data.storage.persistent)this.status('Draft loaded. Server disk is temporary; export a backup after saving.');}
  catch(error){this.status(error.message,true);if(error.status===401)this.auth();if(!this.doc){this.$('#map-loading').textContent=error.message;}}
  finally{this.busy=false;this.updateButtons();if(this.doc)this.$('#map-loading').hidden=true;}
 }
 resetCamera(){const target=this.base.id==='sunnybreak'?{x:-53,y:groundAt(this.base,-53,-30),z:-30}:{x:0,y:groundAt(this.base,0,0),z:0};this.controls.target.set(target.x,target.y+3,target.z);this.camera.position.set(target.x+65,target.y+65,target.z+85);this.controls.update();this.$('#map-view-label').textContent=this.base.name.toUpperCase();this.scene.background=new THREE.Color(this.base.sky);this.scene.fog=new THREE.Fog(this.base.sky,500,1400);}
 async rebuild(){
  if(!this.doc||this.closed)return;const generation=++this.buildGeneration;this.transform.detach();const preview=clone(this.doc.layout),selected=this.doc.record(this.selected);
  if(selected?.source&&!preview.objects.some(o=>o.id===selected.id)&&!['chest','spawn'].includes(this.doc.sources.get(selected.source)?.type))preview.objects.push(selected);
  let map;try{map=compileLayout(this.base,preview);}catch(error){this.status(error.message,true);return;}
  const next=new THREE.Group(),steps=this.base.theme==='royale'?buildIslandSteps(next,map,worldKit):null;
  try{
   if(steps){let end=performance.now()+5;for(let step=steps.next();!step.done;step=steps.next()){if(performance.now()>end){await new Promise(r=>requestAnimationFrame(r));if(this.closed||generation!==this.buildGeneration){disposeMapGroup(next);return;}end=performance.now()+5;}}}else buildArena(next,map,worldKit);
   if(this.closed||generation!==this.buildGeneration){disposeMapGroup(next);return;}
   disposeMapGroup(this.world);this.world.removeFromParent();this.world=next;this.scene.add(next);this.previewMap=map;this.buildMarkers();this.attachSelection();this.drawGrid();this.updateButtons();
  }catch(error){disposeMapGroup(next);this.status('Could not draw map: '+error.message,true);}
 }
 buildMarkers(){disposeMapGroup(this.markerRoot);this.markerRoot.userData.disposed=false;for(const r of this.doc.visibleObjects()){const type=r.source?this.doc.sources.get(r.source)?.type:r.kind;if(!['chest','spawn'].includes(type))continue;const s=r.source?this.doc.sources.get(r.source):null;const point=clone(r);if(s?.type==='spawn')point.position[1]=groundAt(this.previewMap,point.position[0],point.position[2]);const g=makeMapObject({...point,sourceObject:s,origin:s?.position||[0,0,0]},worldKit,{base:this.base,markers:true});g.userData.editorId=r.id;this.markerRoot.add(g);}}
 drawGrid(){if(this.grid){this.grid.removeFromParent();this.grid.geometry.dispose();this.grid.material.dispose();}const size=Math.min(this.base.size*2,600);this.grid=new THREE.GridHelper(size,Math.min(128,Math.round(size/4)),0x52646a,0x6b7b7b);this.grid.position.y=groundAt(this.previewMap,this.controls.target.x,this.controls.target.z)+.025;this.grid.material.transparent=true;this.grid.material.opacity=.18;this.grid.visible=this.gridVisible;this.scene.add(this.grid);}
 attachSelection(){
  if(this.outline){this.outline.removeFromParent();this.outline.geometry.dispose();this.outline.material.dispose();this.outline=null;}
  this.selectedGroup=null;if(!this.selected)return;const r=this.doc.record(this.selected);if(!r||r.removed){this.selected=null;this.renderInspector();return;}
  this.world.traverse(g=>{if(g.userData.editorId===this.selected)this.selectedGroup=g;});this.markerRoot.traverse(g=>{if(g.userData.editorId===this.selected)this.selectedGroup=g;});
  if(!this.selectedGroup)return;this.transform.attach(this.selectedGroup);this.transform.enabled=!this.busy&&!this.locked.has(this.selected);this.transform.setMode(this.mode);this.transform.showX=this.mode!=='rotate';this.transform.showY=true;this.transform.showZ=this.mode!=='rotate';this.transform.showE=false;this.transform.showXYZE=false;this.transform.setTranslationSnap(this.snap||null);this.transform.setRotationSnap(r.collision?Math.PI/2:this.snap?this.rotationSnap*Math.PI/180:null);this.transform.setScaleSnap(this.snap ? .1 : null);
  this.outline=new THREE.BoxHelper(this.selectedGroup,0xf0c67e);this.scene.add(this.outline);this.updateButtons();
 }
 async select(id,focus=false){if(this.closed||this.walking||!this.doc.record(id))return;this.cancelPlacement();this.selected=id;this.renderCatalog();this.renderInspector();await this.rebuild();if(focus)this.focus();}
 focus(){if(!this.selectedGroup)return;const b=new THREE.Box3().setFromObject(this.selectedGroup),center=b.getCenter(new THREE.Vector3()),size=b.getSize(new THREE.Vector3());this.controls.target.copy(center);const distance=Math.max(8,size.length()*1.45);this.camera.position.copy(center).add(new THREE.Vector3(.8,.65,1).normalize().multiplyScalar(distance));this.controls.update();}
 setRay(e){const rect=this.canvas.getBoundingClientRect();this.pointer.set((e.clientX-rect.left)/rect.width*2-1,-(e.clientY-rect.top)/rect.height*2+1);this.camera.updateMatrixWorld();this.raycaster.setFromCamera(this.pointer,this.camera);}
 pointAt(e){if(!this.doc)return null;this.setRay(e);const hits=this.raycaster.intersectObject(this.world,true);return hits[0]?.point?.clone()||this.raycaster.ray.intersectPlane(new THREE.Plane(new THREE.Vector3(0,1,0),-groundAt(this.previewMap,this.controls.target.x,this.controls.target.z)),new THREE.Vector3());}
 pick(e){
  if(!this.doc||this.busy)return;this.setRay(e);const ray=this.raycaster.ray,meshes=this.raycaster.intersectObjects([this.world,this.markerRoot],true);let best=null,distance=meshes[0]?.distance+.25||Infinity;
  for(const hit of meshes){if(hit.distance>distance)break;let node=hit.object;while(node&&!node.userData.editorId)node=node.parent;if(node?.userData.editorId){best=node.userData.editorId;distance=hit.distance;break;}const vertex=(hit.faceIndex||0)*3,ranges=hit.object.userData.objectRanges,objectId=hit.object.userData.objectId||ranges?.find(r=>vertex>=r.start&&vertex<r.start+r.count)?.id,id=this.objectSources.get(objectId);if(id){best=id;distance=hit.distance;break;}}
  for(const b of this.previewMap.boxes){const d=rayBox(ray.origin,ray.direction,b,distance);if(!Number.isFinite(d)||d>=distance)continue;const id=b.editorObject||(b.prop!==undefined?'prop-'+b.prop:b.tree!==undefined?'tree-'+b.tree:b.building!==undefined?'building-'+b.building:'box-'+(this.base.authored||this.base.boxes).findIndex(o=>(o.objectId||'world-'+(this.base.authored||this.base.boxes).indexOf(o))===b.objectId));if(this.doc.record(id)){best=id;distance=d;}}
  if(best)void this.select(best);else {this.selected=null;this.transform.detach();this.selectedGroup=null;this.renderInspector();this.renderCatalog();}
 }
 newRecord(kind,asset=null){const p=prefab(kind);return {id:uuid(),kind,name:asset?.name||p?.name||'Imported model',position:[this.controls.target.x,groundAt(this.previewMap,this.controls.target.x,this.controls.target.z),this.controls.target.z],rotation:0,scale:[1,1,1],collision:!['spawn','chest','bush'].includes(kind),...(p?.color?{color:p.color}:{}),...(asset?{asset:asset.id,dimensions:asset.dimensions}:{})};}
 beginPlacement(kind,asset=null){if(!this.doc||this.busy||this.walking)return;this.cancelPlacement();this.placing=this.newRecord(kind,asset);this.transform.detach();this.ghost=makeMapObject(this.placing,worldKit);this.ghost.traverse(m=>{if(m.isMesh){m.material=m.material.clone();m.material.transparent=true;m.material.opacity=.58;m.material.depthWrite=false;m.userData.ownedMaterial=true;}});this.scene.add(this.ghost);this.status('Click the map to place '+this.placing.name+'. Press Enter to place at the camera target.');this.$('#map-help').textContent='Click map: place object · Escape: cancel · Enter: place here';this.renderCatalog();}
 moveGhost(point){if(!point||!this.ghost)return;const snap=v=>this.snap?Math.round(v/this.snap)*this.snap:v;this.placing.position=[number(snap(point.x)),number(point.y),number(snap(point.z))];this.ghost.position.fromArray(this.placing.position);}
 placeAt(e){if(e)this.moveGhost(this.pointAt(e));if(!this.placing)return;const record=clone(this.placing);if(Math.abs(record.position[0])>this.base.size+12||Math.abs(record.position[2])>this.base.size+12){this.status('Place the object inside the map boundary.',true);return;}this.cancelPlacement();this.commit(record);this.selected=record.id;this.renderInspector();this.renderCatalog();void this.rebuild();}
 cancelPlacement(){this.placing=null;if(this.ghost){this.ghost.userData.abandoned=true;disposeMapGroup(this.ghost);this.ghost.removeFromParent();this.ghost=null;}if(this.root)this.$('#map-help').innerHTML='Click to select · Drag colored handles to edit<br>Right drag: orbit · Middle drag: pan · Scroll: zoom';}
 readTransform(){if(!this.selectedGroup||!this.selected)return null;const r=clone(this.doc.record(this.selected)),g=this.selectedGroup;r.position=g.position.toArray().map(number);r.scale=g.scale.toArray().map(n=>number(Math.max(.1,Math.min(8,n))));r.rotation=number(g.rotation.y*180/Math.PI);if(r.collision)r.rotation=Math.round(r.rotation/90)*90;return r;}
 updateTransformFields(){const r=this.readTransform();if(!r)return;for(const [group,values]of [['position',r.position],['scale',r.scale]])for(let i=0;i<3;i++){const node=this.$(`[data-map-property="${group}"][data-axis="${i}"]`);if(node&&node!==document.activeElement)node.value=values[i];}const angle=this.$('[data-map-property="rotation"]');if(angle)angle.value=r.rotation;this.outline?.update();}
 commit(record){try{this.doc.set(record);this.changed();this.updateTransformFields();this.status('Object updated.');}catch(error){this.status(error.message,true);void this.rebuild();}}
 flushLocal(){clearTimeout(this.autosaveTimer);if(!this.doc)return;try{localStorage.setItem(autosaveKey(this.mapId),JSON.stringify({version:this.version,layout:this.doc.layout,at:Date.now()}));}catch{this.status('Browser autosave is full. Save a server draft or export a backup.',true);}}
 changed(){this.updateButtons();this.renderCatalog();clearTimeout(this.autosaveTimer);this.autosaveTimer=setTimeout(()=>this.flushLocal(),500);}
 localRecovery(){let local;try{local=JSON.parse(localStorage.getItem(autosaveKey(this.mapId)));}catch{}this.localDraft=local;if(local?.layout&&layoutKey(local.layout)!==layoutKey(this.doc.layout)){this.$('#map-local-recovery').innerHTML='<div class="map-local-recovery">A browser autosave is available.<button data-editor-action="restore-local">Restore autosave</button><button data-editor-action="discard-local">Dismiss</button></div>';}else this.$('#map-local-recovery').innerHTML='';}
 renderCatalog(){
  if(!this.doc)return;const q=this.search.toLowerCase().trim(),container=this.$('#map-catalog');this.root.querySelectorAll('[data-editor-tab]').forEach(b=>b.classList.toggle('active',b.dataset.editorTab===this.tab));
  if(this.tab==='scene'){const all=this.doc.visibleObjects().filter(o=>!q||o.name.toLowerCase().includes(q)||o.id.toLowerCase().includes(q));container.innerHTML=all.slice(0,150).map(o=>`<button class="map-scene-row ${o.id===this.selected?'active':''}" data-editor-select="${o.id}" title="${escape(o.name)}"><b>${escape(o.name)}</b><small>${o.source?'Map':'Added'}</small></button>`).join('')+`<p class="map-empty">${all.length} objects${all.length>150?' · Showing the first 150. Search to find others.':''}</p>`;return;}
  const entries=MAP_PREFABS.filter(p=>!q||p.name.toLowerCase().includes(q)||p.category.toLowerCase().includes(q));let html='';for(const category of [...new Set(entries.map(p=>p.category))])html+=`<h3 class="map-palette-group">${category}</h3><div class="map-palette-grid">${entries.filter(p=>p.category===category).map(p=>`<button data-editor-prefab="${p.id}" class="${this.placing?.kind===p.id?'active':''}"><span class="map-object-icon" aria-hidden="true">${icon(p)}</span><span>${escape(p.name)}</span></button>`).join('')}</div>`;
  const models=this.assets.filter(a=>!q||a.name.toLowerCase().includes(q));if(models.length)html+=`<h3 class="map-palette-group">Imported models</h3><div class="map-palette-grid">${models.map(a=>`<button data-editor-asset="${a.id}"><span class="map-object-icon" aria-hidden="true">⬡</span><span>${escape(a.name)}</span></button>`).join('')}</div>`;
  container.innerHTML=html||'<p class="map-empty">No objects match your search.</p>';
 }
 renderInspector(){
  const r=this.doc?.record(this.selected);if(!r||r.removed){this.$('#map-inspector').innerHTML='<p class="map-empty">Select an object in the map or Scene list.<br><br>Choose an object from the catalog, then click the map to place it.</p>';return;}
  const vectorFields=(group,values)=>`<div class="map-property-grid">${['X','Y','Z'].map((axis,i)=>`<label>${axis}<input type="number" step="${group==='scale'?.1:.25}" data-map-property="${group}" data-axis="${i}" aria-label="${group} ${axis}" value="${values[i]}" ${group==='scale'?'min=".1" max="8"':''}></label>`).join('')}</div>`;
  const locked=this.locked.has(r.id),src=r.source?this.doc.sources.get(r.source):null;
  this.$('#map-inspector').innerHTML=`<label>Name<input data-map-property="name" maxlength="60" value="${escape(r.name)}"></label><section class="map-inspector-section"><h3>Position · meters</h3>${vectorFields('position',r.position)}</section><section class="map-inspector-section"><h3>Rotation · degrees</h3><label>Y / heading<input type="number" data-map-property="rotation" step="${r.collision?90:15}" value="${r.rotation}"></label><small>${r.collision?'Solid objects use 90° turns for exact collision.':'Free rotation. Grid snapping uses 15° steps.'}</small></section><section class="map-inspector-section"><h3>Scale</h3>${vectorFields('scale',r.scale)}</section>${!['spawn','chest'].includes(src?.type||r.kind)?`<label class="map-toggle-line"><input type="checkbox" data-map-property="collision" ${r.collision?'checked':''}>Solid collision</label><label>Color / tint<input type="color" data-map-property="color" value="${r.color||'#82928f'}"></label><button data-editor-action="reset-color">Original colors</button>`:''}<label class="map-toggle-line"><input type="checkbox" data-map-property="locked" ${locked?'checked':''}>Lock selection</label><div class="map-inspector-actions"><button data-editor-action="duplicate">Duplicate</button><button data-editor-action="focus">Focus</button>${r.source&&r.id===r.source?'<button data-editor-action="restore">Restore original</button>':''}<button class="danger" data-editor-action="delete">Delete</button></div><div class="map-hint-card">${src?.type==='building'?'Building movement includes its furniture, stairs and loot anchors.':r.kind==='model'?'Imported models use a box collider. Turn collision off for decorative scenery.':r.kind==='shield-barrel'?'Works as a shield barrel in Royale.':(src?.type||r.kind)==='chest'?'Loot is rolled by the match host in Royale.':'Changes stay in this draft until you publish.'}</div>`;
  this.$('#map-inspector').querySelectorAll('[data-map-property]').forEach(n=>{if(n.dataset.mapProperty!=='locked')n.disabled=locked;});
 }
 updateButtons(){if(!this.root)return;const dirty=this.doc?.dirty;this.$('#map-save-state').textContent=this.busy?'Working…':dirty?'Unsaved draft':'Draft saved';this.$('[data-editor-action="undo"]').disabled=this.busy||!this.doc?.undoStack.length;this.$('[data-editor-action="redo"]').disabled=this.busy||!this.doc?.redoStack.length;for(const a of ['save','publish','walk','import','model','export'])this.$(`[data-editor-action="${a}"]`).disabled=this.busy||!this.doc;this.$('#map-picker').disabled=this.busy;this.root.querySelectorAll('[data-map-property]').forEach(n=>n.disabled=this.busy||(n.dataset.mapProperty!=='locked'&&this.locked.has(this.selected)));if(this.transform)this.transform.enabled=!this.busy&&!this.walking&&!this.locked.has(this.selected);this.$('#map-count').textContent=this.doc?`${this.doc.layout.objects.filter(o=>(!o.source||o.id!==o.source)&&!o.removed).length}/250 added · Published r${this.publishedRevision||0}`:'';}
 status(text,error=false){if(this.closed)return;const node=this.$('#map-status');node.textContent=text;node.classList.toggle('error',error);}
 async click(e){
  if(this.busy)return;
  const b=e.target.closest('button');if(!b||b.disabled)return;if(b.dataset.editorTab){this.tab=b.dataset.editorTab;this.renderCatalog();return;}if(b.dataset.editorSelect){await this.select(b.dataset.editorSelect,true);return;}if(b.dataset.editorPrefab){this.beginPlacement(b.dataset.editorPrefab);return;}if(b.dataset.editorAsset){this.beginPlacement('model',this.assets.find(a=>a.id===b.dataset.editorAsset));return;}const action=b.dataset.editorAction;if(!action)return;
  if(action.startsWith('mode-')){this.mode=action.slice(5);this.attachSelection();this.root.querySelectorAll('[data-editor-action^="mode-"]').forEach(n=>n.classList.toggle('active',n.dataset.editorAction===action));return;}
  if(action==='focus'){this.focus();return;}if(action==='top'){const p=this.controls.target;this.camera.position.set(p.x,p.y+Math.max(45,this.base.size*.55),p.z+.01);this.controls.update();return;}
  if(action==='grid'){this.gridVisible=!this.gridVisible;if(this.grid)this.grid.visible=this.gridVisible;b.classList.toggle('active',this.gridVisible);return;}
  if(action==='snap'){this.snap=this.snap===1?.25:this.snap===.25?0:1;b.textContent='Snap: '+(this.snap?this.snap+'m':'off');this.attachSelection();return;}
  if(action==='undo'||action==='redo'){this.cancelPlacement();this.doc[action]();this.changed();this.renderInspector();await this.rebuild();return;}
  if(action==='walk'){this.walking?this.endWalk():this.startWalk();return;}
  if(action==='export'){this.exportMap();return;}if(action==='import'){this.$('#map-import-file').click();return;}if(action==='model'){this.$('#map-model-file').click();return;}
  if(action==='save'||action==='publish'){await this.save(action==='publish');return;}
  if(action==='close'){if(this.busy){this.status('Wait for the current save or import to finish.');return;}if(this.doc?.dirty){this.confirm('Leave with unsaved changes?','Your browser autosave remains here. Save the draft or export a backup to keep a separate copy.',[['Keep editing',()=>{}],['Save & exit',async()=>{if(await this.save(false))this.close();}],['Exit',()=>this.close()]]);}else this.close();return;}
  if(action==='restore-local'){try{this.doc.change(validateLayout(this.localDraft.layout,this.mapId));this.changed();this.$('#map-local-recovery').innerHTML='';await this.rebuild();this.status('Browser autosave restored. Save the draft when ready.');}catch(error){this.status(error.message,true);}return;}
  if(action==='discard-local'){this.$('#map-local-recovery').innerHTML='';return;}
  const r=this.doc?.record(this.selected);if(!r||this.locked.has(r.id)){this.status('Select an unlocked object first.');return;}
  if(action==='duplicate'){const copy=clone(r);copy.id=uuid();copy.name=(r.name+' copy').slice(0,60);copy.position[0]+=3;this.commit(copy);this.selected=copy.id;this.renderInspector();await this.rebuild();}
  if(action==='delete'){this.doc.remove(r.id);this.selected=null;this.changed();this.renderInspector();await this.rebuild();}
  if(action==='restore'){this.doc.restore(r.id);this.changed();this.renderInspector();await this.rebuild();}
  if(action==='reset-color'){const copy=clone(r);delete copy.color;this.commit(copy);await this.rebuild();}
 }
 async change(e){
  if(this.busy)return;
  if(e.target.id==='map-picker'){const next=e.target.value,old=this.mapId;if(this.doc?.dirty){e.target.value=old;this.confirm('Switch maps?','Save this draft before switching, or keep it in the browser autosave.',[['Keep editing',()=>{}],['Save & switch',async()=>{if(await this.save(false))await this.loadMap(next);}],['Switch',()=>this.loadMap(next)]]);}else await this.loadMap(next);return;}
  if(e.target.id==='map-import-file'){const f=e.target.files[0];e.target.value='';if(f)await this.importMap(f);return;}if(e.target.id==='map-model-file'){const f=e.target.files[0];e.target.value='';if(f)await this.importModel(f);return;}
  const property=e.target.dataset.mapProperty,r=this.doc?.record(this.selected);if(!property||!r)return;if(property==='locked'){e.target.checked?this.locked.add(r.id):this.locked.delete(r.id);this.renderInspector();this.attachSelection();return;}
  const next=clone(r);if(['position','scale'].includes(property))next[property][Number(e.target.dataset.axis)]=Number(e.target.value);else if(property==='rotation')next.rotation=Number(e.target.value);else if(property==='collision'){next.collision=e.target.checked;if(next.collision)next.rotation=Math.round(next.rotation/90)*90;}else next[property]=e.target.value;
  this.commit(next);this.renderInspector();await this.rebuild();
 }
 key(e){
  if(this.closed||!this.root.isConnected)return;if(this.$('.map-confirm')){if(e.key==='Escape'){e.preventDefault();this.$('.map-confirm').remove();}return;}if(e.target.matches('input,textarea,select,[contenteditable]'))return;
  if(this.walking){this.keys.add(e.code);if(['KeyW','KeyA','KeyS','KeyD','Space','ShiftLeft','ShiftRight'].includes(e.code)){e.preventDefault();e.stopImmediatePropagation();}if(e.code==='Escape'){e.preventDefault();this.endWalk();}return;}
  if(this.busy||!this.doc)return;const cmd=e.ctrlKey||e.metaKey;let action=null;
  if(cmd&&e.code==='KeyZ')action=e.shiftKey?'redo':'undo';else if(cmd&&e.code==='KeyY')action='redo';else if(cmd&&e.code==='KeyD')action='duplicate';else if(cmd&&e.code==='KeyS')action='save';else if(['Delete','Backspace'].includes(e.code))action='delete';else if(e.code==='KeyW')action='mode-translate';else if(e.code==='KeyE')action='mode-rotate';else if(e.code==='KeyR')action='mode-scale';else if(e.code==='KeyF')action='focus';else if(e.code==='Escape'){this.cancelPlacement();this.selected=null;this.transform.detach();this.renderInspector();this.renderCatalog();e.preventDefault();return;}else if(e.code==='Enter'&&this.placing){this.placeAt();e.preventDefault();return;}
  if(action){e.preventDefault();e.stopImmediatePropagation();const b=this.root.querySelector(`[data-editor-action="${action}"]`);if(b)b.click();else void this.click({target:{closest:()=>({dataset:{editorAction:action}})}});}
 }
 async save(publish){
  if(this.busy||!this.doc)return false;this.cancelPlacement();this.busy=true;this.updateButtons();this.status(publish?'Publishing map for future rounds…':'Saving server draft…');
  try{const data=await this.api(publish?'publish':'save',{mapId:this.mapId,layout:this.doc.layout,expectedVersion:this.version});this.version=data.draftVersion;this.publishedRevision=data.revision;this.publishedLayout=data.published;this.doc.markSaved();try{localStorage.setItem(autosaveKey(this.mapId),JSON.stringify({version:this.version,layout:this.doc.layout,at:Date.now()}));}catch{}this.status(publish?'Map published. Ongoing matches keep their current layout; new rounds use this version.':'Server draft saved.');if(!data.storage.persistent)this.status((publish?'Map published. ':'Draft saved. ')+'Export a backup: this server has temporary storage.');return true;}
  catch(error){this.status(error.message,true);if(error.status===401)this.auth();return false;}finally{this.busy=false;this.updateButtons();}
 }
 exportMap(){if(!this.doc)return;const blob=new Blob([JSON.stringify(this.doc.layout,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=this.mapId+'-map.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);this.status('Map exported. Model files remain in your server model library.');}
 async importMap(file){try{if(file.size>1_000_000)throw Error('Map files must be under 1 MB.');const layout=validateLayout(JSON.parse(await file.text()),this.mapId);compileLayout(this.base,layout);for(const o of layout.objects)if(o.kind==='model'&&!this.assets.some(a=>a.id===o.asset))throw Error('Import the missing GLB models before importing this map.');this.doc.change(layout);this.selected=null;this.changed();this.renderInspector();await this.rebuild();this.status('Map imported into the draft. Save or publish when ready.');}catch(error){this.status(error.message,true);}}
 async importModel(file){
  if(this.busy)return;this.busy=true;this.updateButtons();this.status('Reading model…');
  try{if(!file.name.toLowerCase().endsWith('.glb')||file.size>8*1024*1024)throw Error('Choose a self-contained GLB model up to 8 MB.');const bytes=await file.arrayBuffer();const header=new DataView(bytes);if(bytes.byteLength<20||header.getUint32(0,true)!==0x46546c67)throw Error('This is not a GLB model.');const jsonLength=header.getUint32(12,true);if(jsonLength>600000||jsonLength+20>bytes.byteLength)throw Error('Model metadata exceeds the limit.');const json=JSON.parse(new TextDecoder().decode(bytes.slice(20,20+jsonLength)));if((json.buffers||[]).some(b=>b.uri)||(json.images||[]).some(i=>i.uri))throw Error('Export with all geometry and textures embedded.');let triangles=0;for(const m of json.meshes||[])for(const p of m.primitives||[])triangles+=(json.accessors?.[p.indices??p.attributes?.POSITION]?.count||0)/3;if(triangles>60000)throw Error('Simplify to 60,000 triangles or fewer before importing.');
   const model=await parseModel(bytes);this.status('Saving imported model…');const array=new Uint8Array(bytes),chunks=[];for(let i=0;i<array.length;i+=32768)chunks.push(String.fromCharCode(...array.subarray(i,i+32768)));const result=await this.owner.request('/map-assets',{method:'POST',body:JSON.stringify({token:this.owner.token,name:file.name.replace(/\.glb$/i,''),dimensions:model.dimensions,bytes:btoa(chunks.join(''))})});registerModel(result.asset.id,model);if(!this.assets.some(a=>a.id===result.asset.id))this.assets.push(result.asset);this.renderCatalog();this.status('Model imported. Select it under Imported models to place it.');
  }catch(error){this.status(error.message,true);if(error.status===401)this.auth();}finally{this.busy=false;this.updateButtons();}
 }
 confirm(title,text,actions){this.$('.map-confirm')?.remove();const overlay=document.createElement('div');overlay.className='map-confirm';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.innerHTML=`<div class="map-confirm-card"><h2>${escape(title)}</h2><p>${escape(text)}</p><div class="map-confirm-actions">${actions.map(([label],i)=>`<button data-confirm-index="${i}">${escape(label)}</button>`).join('')}</div></div>`;this.root.append(overlay);overlay.addEventListener('click',e=>{const index=e.target.dataset.confirmIndex;if(index===undefined)return;overlay.remove();void actions[Number(index)][1]();});overlay.querySelector('button')?.focus();}
 auth(){this.$('.map-confirm')?.remove();const overlay=document.createElement('div');overlay.className='map-confirm';overlay.setAttribute('role','dialog');overlay.setAttribute('aria-modal','true');overlay.innerHTML='<form class="map-confirm-card"><h2>Unlock Owner Access</h2><p>Your editing session is still here. Enter your access code to save or publish.</p><label>Access code<input type="password" inputmode="numeric" pattern="[0-9]{12,32}" minlength="12" maxlength="32" required autocomplete="off"></label><p class="map-auth-error" role="alert"></p><div class="map-confirm-actions"><button type="button">Keep editing</button><button class="primary" type="submit">Unlock</button></div></form>';this.root.append(overlay);overlay.querySelector('[type=button]').onclick=()=>overlay.remove();overlay.querySelector('form').onsubmit=async e=>{e.preventDefault();const input=overlay.querySelector('input'),button=overlay.querySelector('[type=submit]');button.disabled=true;try{const res=await this.owner.request('/login',{method:'POST',body:JSON.stringify({code:input.value})});input.value='';this.owner.token=res.token;this.owner.expires=res.expires;overlay.remove();if(!this.doc)await this.loadMap(this.$('#map-picker').value);this.status('Owner access unlocked. You can save or publish now.');}catch(error){overlay.querySelector('.map-auth-error').textContent=error.message;button.disabled=false;}};overlay.querySelector('input').focus();}
 startWalk(){if(!this.doc||this.busy)return;this.cancelPlacement();const x=this.controls.target.x,z=this.controls.target.z;let spot=null;for(let radius=0;radius<=20&&!spot;radius+=2)for(let angle=0;angle<8;angle++){const px=x+Math.cos(angle*Math.PI/4)*radius,pz=z+Math.sin(angle*Math.PI/4)*radius,p={x:px,y:groundAt(this.previewMap,px,pz),z:pz};if(canStand(this.previewMap,p)){spot=p;break;}}if(!spot){this.status('No clear standing space here. Move the camera to an open area.',true);return;}
  this.walkCamera={position:this.camera.position.clone(),target:this.controls.target.clone()};this.walkPlayer={...spot,vx:0,vz:0,vy:0,yaw:0,pitch:0,grounded:true,health:100,weapon:'sprinter',slot:0,stamina:100};this.walking=true;this.controls.enabled=false;this.transform.detach();this.keys.clear();this.$('[data-editor-action="walk"]').textContent='Stop test';this.$('.map-walk-reticle').hidden=false;this.$('#map-help').textContent='WASD: move · Space: jump · Shift: sprint · Escape: return to editing';this.status('Testing movement and collision in this draft. Click the view for mouse look.');void this.canvas.requestPointerLock()?.catch(()=>this.status('Click the view to enable mouse look.'));this.canvas.focus();this.listen(this.canvas,'click',()=>{if(this.walking&&document.pointerLockElement!==this.canvas)void this.canvas.requestPointerLock()?.catch(()=>{});});}
 walk(dt){const p=this.walkPlayer;movePlayer(p,{forward:(this.keys.has('KeyW')?1:0)-(this.keys.has('KeyS')?1:0),strafe:(this.keys.has('KeyD')?1:0)-(this.keys.has('KeyA')?1:0),yaw:p.yaw,pitch:p.pitch,jump:this.keys.has('Space'),sprint:this.keys.has('ShiftLeft')||this.keys.has('ShiftRight'),crouch:false,aim:false},this.previewMap,dt);this.camera.position.set(p.x,p.y+EYE,p.z);this.camera.rotation.order='YXZ';this.camera.rotation.set(p.pitch,p.yaw,0);}
 endWalk(){if(!this.walking)return;this.walking=false;if(document.pointerLockElement===this.canvas)document.exitPointerLock();this.keys.clear();this.controls.enabled=true;this.camera.position.copy(this.walkCamera.position);this.controls.target.copy(this.walkCamera.target);this.controls.update();this.$('[data-editor-action="walk"]').textContent='Test walk';this.$('.map-walk-reticle').hidden=true;this.$('#map-help').innerHTML='Click to select · Drag colored handles to edit<br>Right drag: orbit · Middle drag: pan · Scroll: zoom';this.attachSelection();this.status('Returned to editing.');}
 close(){if(this.closed)return;this.endWalk();try{if(this.doc?.dirty)localStorage.setItem(autosaveKey(this.mapId),JSON.stringify({version:this.version,layout:this.doc.layout,at:Date.now()}));}catch{}this.closed=true;this.buildGeneration++;clearTimeout(this.autosaveTimer);cancelAnimationFrame(this.raf);for(const off of this.listeners)off();this.resizeObserver?.disconnect();this.transform?.dispose();this.controls?.dispose();this.cancelPlacement();if(this.world)disposeMapGroup(this.world);if(this.markerRoot)disposeMapGroup(this.markerRoot);if(this.outline){this.outline.geometry.dispose();this.outline.material.dispose();}if(this.grid){this.grid.geometry.dispose();this.grid.material.dispose();}this.renderer?.dispose();this.renderer?.forceContextLoss();this.root.remove();this.onClose?.();}
}
