import {mapVaults,vaultOpen} from './vaults.js';
import {bossMapMarkers} from './bosses.js';
import {nearbyItems} from './nearby-items.js';
import {CROWN_ICON} from './crowns.js';
import {bossCachePrompt} from './season-world.js';
import {pickupNeedsSwap} from './field-refinement.js';
const setText=(node,value)=>{if(node&&node.textContent!==String(value))node.textContent=value;};
import {SHADOWSTEP,shadowRechargeState} from './shadowstep.js';
import {rigRechargeState} from './season-one.js';
import {frontierPrompt,keycardRoute} from './frontier-world.js';
import {visibleMarkers} from './team-markers.js';
import {REVIVE_RULES,reviveAccessible} from './team-survival.js';
import {canFight} from './stance.js';
import {inventoryActionForSlot} from './keybinds.js';
import {teammates,isTeamRoyale,teamStyle} from './teams.js';
import {getMap} from './maps.js';
import {buildIcon} from './building-ui.js';
import {gun} from './data.js';
import {ITEMS,RARITIES,itemInfo,transportAt,ammoType} from './royale-data.js';
import {ROYALE_MAP} from './royale-map.js';
import {lootHeight} from './loot-motion.js';
import {wallDistance,dist} from './physics.js';
import {groundAt,terrainColor} from './terrain.js';
const escape=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export class RoyaleUI{
 constructor(preview){
  this.preview=preview;this.waypoint=null;this.lastKey='';
  document.querySelector('#hud').insertAdjacentHTML('beforeend',`<div id="royale-hud" hidden>
   <div id="duo-markers" aria-live="polite"></div><div id="downed-status" role="status" hidden></div><div class="royale-compass" id="royale-compass"></div>
   <div class="royale-map-stack"><button class="royale-minimap" data-action="royale-map" aria-label="Open island map"><canvas id="royale-mini" width="260" height="260"></canvas><span id="royale-phase">STORM 1</span></button><div class="royale-map-stats" aria-label="Battle Royale standings"><span><b id="royale-alive">32</b> ALIVE</span><span><b id="royale-elims">0</b> ELIMS</span><span class="royale-spectator-count" hidden><svg viewBox="0 0 24 24" aria-hidden="true"><path d="M2 12s4-7 10-7 10 7 10 7-4 7-10 7S2 12 2 12Z"/><circle cx="12" cy="12" r="3"/></svg><b id="royale-watch-count">0</b></span></div></div>
   <div class="royale-storm-warning" id="royale-storm-warning" role="status"></div>
   <div class="royale-flight" id="royale-flight"><button class="flight-close" data-action="royale-close-flight" id="royale-flight-close" aria-label="Close flight tips">L Close</button><span class="eyebrow">KESTREL TACTICAL AIRLIFT</span><strong id="royale-flight-title"></strong><p id="royale-flight-help"></p><button data-action="royale-jump" class="primary" id="royale-flight-button">JUMP</button></div>
   <div id="keycard-guide" class="keycard-guide" hidden></div><div class="royale-prompt" id="royale-prompt" role="status"></div>
   <div class="royale-vitals"><div class="royale-meter stamina"><span>↟ STAMINA</span><b id="royale-stamina">100</b><i id="royale-stamina-fill"></i></div></div>
   <div class="royale-hotbar" id="royale-hotbar" role="group" aria-label="Inventory slots"></div>
   <div class="royale-use" id="royale-use"><span id="royale-use-label"></span><div><i id="royale-use-fill"></i></div></div>
   <div class="royale-mobile"><button data-action="duo-marker">MARK</button><button data-action="duo-danger">DANGER</button><button data-touch="sprint" aria-label="Hold to sprint">SPRINT</button><button data-touch="interact" aria-label="Hold to search or pick up">USE / TAKE</button></div>
  </div>`);
  this.root=document.querySelector('#royale-hud');
  this.root.insertAdjacentHTML('beforeend','<div class="duo-hud" id="duo-hud" hidden></div>');
 }
 dismissFlight(){this.flightDismissed=true;document.getElementById('royale-flight').hidden=true;}
 slotMarkup(p,inventory=false){const slots= (p.inventory||Array(6).fill(null)).map((item,index)=>{
  const info=itemInfo(item),rarity=RARITIES[item?.rarity||0];
  return `<button class="royale-slot ${index===p.slot?'selected':''}" data-royale-slot="${index}" draggable="false" style="--rarity:${item?info.color:'#58636c'}" aria-label="${index===0?'Pickaxe':'Slot '+index}: ${escape(info.name)}" aria-pressed="${index===p.slot}"><kbd>${escape(this.label?.(inventoryActionForSlot(index))||(index===0?'Pickaxe':index))}</kbd>${item?`<span class="item-art"><img src="${this.preview(item)}" alt="${escape(info.name)}" draggable="false">${['jumpRig','shadowstep'].includes(item.id)?`<svg class="rig-recharge" data-rig-slot="${index}" viewBox="0 0 60 60" role="img" aria-label="Jump Rig ready" hidden><circle class="rig-track" cx="30" cy="30" r="27"/><circle class="rig-fill" cx="30" cy="30" r="27" pathLength="100"/></svg><small class="rig-seconds" hidden></small>`:''}</span>`:'<span class="empty-slot-mark">＋</span>'}<span class="slot-name" title="${escape(info.name)}">${escape(info.name)}</span>${item?`<b>${item.pickaxe?'∞':item.weapon?item.ammo:['jumpRig','shadowstep'].includes(item.id)?(item.charges??(item.id==='shadowstep'?SHADOWSTEP.charges:3))+'/'+(item.id==='shadowstep'?SHADOWSTEP.charges:3):item.id==='anchorWinch'?'∞':item.count+'×'}</b>`:''}${inventory&&item?`<small>${item.weapon||['jumpRig','shadowstep'].includes(item.id)?rarity.name:'Utility'}${item.weapon?' · '+'★'.repeat((item.rarity||0)+1):''}</small>`:''}</button>`;
 });return slots[0]+'<div class="royale-item-slots">'+slots.slice(1).join('')+'</div>';}
 mapHTML(){return `<p class="hint">Choose a landing spot or plan your next rotation. Click the island to mark a waypoint.</p><canvas id="royale-fullmap" class="royale-fullmap" width="720" height="720" aria-label="Ravel Coast island map"></canvas><div class="map-legend"><span>● You</span><span>◯ Safe area</span><span>◌ Next circle</span><span>◆ Supply</span><span>◇ Landmark</span></div><div class="split-actions"><button data-action="royale-clear-marker">Clear marker</button><button class="primary" data-action="resume">RETURN TO GAME</button></div>`;}
 crownHTML(p){return `<div class="inventory-crown" ${p.crown?'':'hidden'}>${CROWN_ICON}<div><strong>Victory Crown</strong><small>${p.crownWins||0} crowned victories · Season 1</small></div><button data-action="crown-drop">DROP</button></div>`;}
 ammoHTML(p){return Object.entries(p.materials||{}).map(([id,count])=>`<div class="inventory-ammo resource-count">${buildIcon(id)}<span>${id}</span><b>${count}</b><button data-supply-drop="${id}-half" ${count?'':'disabled'}>½</button><button data-supply-drop="${id}-all" ${count?'':'disabled'}>ALL</button></div>`).join('')+Object.entries(p.bank||{}).map(([id,count])=>`<div class="inventory-ammo" tabindex="0" title="${count} ${id} ammo" aria-label="${count} ${id} ammo"><img src="${this.preview({id,ammoType:id})}" alt=""><span>${escape(id)}</span><b>${count}</b><button data-supply-drop="${id}-half" ${count?'':'disabled'}>½</button><button data-supply-drop="${id}-all" ${count?'':'disabled'}>ALL</button></div>`).join('');}
 inspectHTML(p){
  const item=p.inventory[p.slot],info=itemInfo(item);if(item?.pickaxe)return '<div class="inspect-empty"><h3>PICKAXE</h3>Harvest wood, brick and metal. Dedicated pickaxe slot. Cannot be dropped or replaced.</div>';if(!item)return '<div class="inspect-empty">Select an item to inspect it.</div>';
  const rarity=RARITIES[item.rarity||0],w=item.weapon?gun(p):null,def=ITEMS[item.id];
  return `<div class="inspect-heading" style="--rarity:${info.color}"><span>${item.weapon?rarity.name+' · '+info.role:['jumpRig','anchorWinch','shadowstep'].includes(item.id)?'MYTHIC · MOBILITY':'UTILITY'}</span><h3>${escape(info.name)}</h3><img src="${this.preview(item)}" alt="${escape(info.name)}"></div><p>${escape(w?.desc||({winch:'Aim at a surface within 75 metres and fire a plunger to pull yourself toward it. Unlimited uses, with a 1.54-second cooldown. A red cross means no reachable surface. Latching resets your fall distance; long falls after release can still hurt.',shadowstep:'Six 9-metre directional dashes. One charge returns every 10 seconds. Briefly breaks bots’ target lock. Fire while moving to dash that way, or stand still to dash forward. Walls stop the dash. Using Shadowstep protects the resulting fall until you land.',veil:'Deploys six seconds of smoke. Blocks everyone’s sight, including bosses. Three uses.',jumpRig:'Three directional boost charges. One charge returns every 12 seconds. Fall protection covers the boost. Fire to use.',smoke:'Deploys 12 seconds of visual cover. Bots cannot see through it. Bullets still pass through.',keycard:'Equip to follow the route to its boss’s vault. Hold Use at the reader to unlock it.',scanner:'Reveals nearby last-known enemy positions for 8 seconds.',heal:'Restores health.',shield:'Restores shield protection.',splash:'Restores nearby health and shields.',popper:'A throwable grenade with a short fuse.',impulse:'Launches you into the air.',launchpad:'Place a reusable launch pad.'}[def?.kind]))}</p>${w?`<dl class="weapon-stats"><div><dt>Damage</dt><dd>${(w.damage*w.pellets*(w.burst||1)).toFixed(0)}${w.pellets>1?' total pellets':w.burst?' per burst':''}</dd></div><div><dt>Fire rate</dt><dd>${(1/w.interval).toFixed(1)} / s</dd></div><div><dt>Magazine</dt><dd>${w.magazine}</dd></div><div><dt>Reload</dt><dd>${w.reload.toFixed(2)} s</dd></div><div><dt>Ammo</dt><dd>${ammoType(item.id)}</dd></div><div><dt>Reserve</dt><dd>${p.bank[ammoType(item.id)]||0}</dd></div></dl>`:`<dl class="weapon-stats"><div><dt>Use time</dt><dd>${def?.duration||0}s</dd></div><div><dt>Stack</dt><dd>${item.count} / ${def?.stack||1}</dd></div>${def?.amount?`<div><dt>Restores</dt><dd>${def.amount}</dd></div>`:''}</dl>`}`;
 }
 inventoryHTML(p){return `<div class="inventory-content"><section class="inventory-ammo-section">${this.crownHTML(p)}${p.training?'<h3>RANGE LOADOUT</h3><select data-training-weapon>'+['sprinter','scatter','needle','zipper','thumper','anchor','duet','pip','peeper','doubleyolk','comet'].map(id=>'<option value="'+id+'">'+itemInfo({id,weapon:true}).name+'</option>').join('')+'</select>':''}<h3>RESOURCES & AMMO</h3><p>Drop half or all with the buttons below.</p><div class="ammo-bank">${this.ammoHTML(p)}</div></section><section class="inventory-inspect" id="inventory-inspect" ${this.inspect?'':'hidden'}>${this.inspectHTML(p)}</section><section class="inventory-equipment"><div class="inventory-section-title"><h3>EQUIPMENT</h3><span>Drag left to drop · Drag onto another slot to swap</span></div><div class="royale-inventory-grid">${this.slotMarkup(p,true)}</div><p id="inventory-selected-name">${escape(itemInfo(p.inventory[p.slot]).name)}</p></section></div><footer class="inventory-actions"><button data-action="royale-split">SPLIT</button><button data-action="royale-drop-one">DROP ONE</button><button data-action="royale-drop">DROP STACK</button><button data-action="royale-inspect" aria-pressed="${!!this.inspect}">INSPECT</button><button data-action="resume">BACK</button></footer>`;}
 updateRigRings(root,p){if(!root||!p)return;for(const ring of root.querySelectorAll('[data-rig-slot]')){const item=p.inventory?.[Number(ring.dataset.rigSlot)],r=(item?.id==='shadowstep'?shadowRechargeState:rigRechargeState)(item,this.time||0);ring.toggleAttribute('hidden',!r.active);ring.style.display=r.active?'block':'none';ring.querySelector('.rig-fill').style.strokeDashoffset=String(100*(1-r.progress));ring.setAttribute('aria-label',`Next ${item.id==='shadowstep'?'Shadowstep':'Jump Rig'} charge in ${Math.ceil(r.remaining)} seconds`);const label=ring.nextElementSibling;label.hidden=!r.active;label.textContent=Math.ceil(r.remaining)+'s';}}
 updateInventory(p){
  const grid=document.querySelector('.royale-inventory-grid');if(!grid||!p||this.dragging)return;
  const key=JSON.stringify([p.inventory,p.slot,p.bank,p.materials,this.inspect,[0,1,2,3,4,5].map(i=>this.label?.(inventoryActionForSlot(i)))]);
  if(this.inventoryKey===key){this.updateRigRings(grid,p);return;}this.inventoryKey=key;grid.innerHTML=this.slotMarkup(p,true);this.updateRigRings(grid,p);
  document.querySelector('.ammo-bank').innerHTML=this.ammoHTML(p);
  const inspect=document.querySelector('#inventory-inspect');inspect.hidden=!this.inspect;inspect.innerHTML=this.inspectHTML(p);
  document.querySelector('#inventory-selected-name').textContent=itemInfo(p.inventory[p.slot]).name;
  const item=p.inventory[p.slot];document.querySelector('[data-action="royale-split"]').disabled=!item||item.weapon||item.count<2||p.inventory.every(Boolean);
  document.querySelector('[data-action="royale-drop-one"]').disabled=!item||item.pickaxe;
  document.querySelector('#dialog [data-action="royale-drop"]').disabled=!item||item.pickaxe;
  document.querySelector('[data-action="royale-inspect"]').setAttribute('aria-pressed',String(!!this.inspect));
 }
 drawMap(canvas,state,p,full=false){
  if(!canvas||!state.royale)return;
  const c=canvas.getContext('2d'),w=canvas.width,h=canvas.height,map=getMap(state.royale.practice?'sunnybreak':state.options.map),size=map.size*2,s=w/size,r=state.royale,key=map.id+':'+(map.revision||0)+':'+w;
  const point=(x,z)=>[(x+map.size)*s,(z+map.size)*s];
  c.clearRect(0,0,w,h);
  this.mapBackgrounds??=new Map();
  if(!this.mapBackgrounds.has(key)){
   const bg=document.createElement('canvas');bg.width=w;bg.height=h;const b=bg.getContext('2d');
   for(let z=-map.size;z<map.size;z+=2)for(let x=-map.size;x<map.size;x+=2){const [px,pz]=point(x,z),height=groundAt(map,x,z);b.fillStyle='#'+terrainColor(map,x,z).toString(16).padStart(6,'0');b.fillRect(px,pz,2*s+1,2*s+1);
    const shade=Math.max(-.2,Math.min(.18,(groundAt(map,x-2,z-2)-height)*.055));if(Math.abs(shade)>.025){b.fillStyle=shade>0?`rgba(255,249,207,${shade})`:`rgba(24,55,48,${-shade})`;b.fillRect(px,pz,2*s+1,2*s+1);}}
   b.lineJoin='round';b.lineCap='round';for(const road of map.roads){b.strokeStyle=road.kind==='path'?'#bfb88d':'#b1b8a6';b.lineWidth=road.width*s;b.beginPath();road.points.forEach(([x,z],i)=>i?b.lineTo(...point(x,z)):b.moveTo(...point(x,z)));b.stroke();}
   b.fillStyle='#547b5c';for(const t of map.trees){const [x,z]=point(t.x,t.z);b.beginPath();b.arc(x,z,2*s,0,Math.PI*2);b.fill();}
   for(const building of map.buildings){const [x,z]=point(building.x-building.w/2,building.z-building.d/2);b.fillStyle='#415f65';b.fillRect(x+1,z+1,building.w*s,building.d*s);b.fillStyle=building.kind==='factory'?'#acc3c7':building.kind==='farm'?'#c79872':'#ebd3a8';b.fillRect(x,z,building.w*s,building.d*s);}
   for(const bridge of map.boxes.filter(o=>o.kind==='bridge'&&o.h<.5)){const [x,z]=point(bridge.x-bridge.w/2,bridge.z-bridge.d/2);b.fillStyle='#cfb887';b.fillRect(x,z,bridge.w*s,bridge.d*s);}
   this.mapBackgrounds.set(key,bg);
  }
  c.drawImage(this.mapBackgrounds.get(key),0,0);
  if(!full){c.font='800 8px system-ui';c.textAlign='center';c.fillStyle='#fff5d8';c.strokeStyle='#294f4b';c.lineWidth=2;for(const poi of map.districts){const [x,z]=point(poi.x,poi.z),name=poi.name.split(' ')[0].toUpperCase();c.strokeText(name,x,z-7);c.fillText(name,x,z-7);}}
  if(r.storm?.active){const q=r.storm,[x,z]=point(q.x,q.z);c.save();c.fillStyle='#725ac277';c.beginPath();c.rect(0,0,w,h);c.moveTo(x+q.radius*s,z);c.arc(x,z,q.radius*s,0,Math.PI*2,true);c.fill('evenodd');c.strokeStyle='#f6f5ff';c.lineWidth=full?3:2;c.beginPath();c.arc(x,z,q.radius*s,0,Math.PI*2);c.stroke();const [nx,nz]=point(q.nextX,q.nextZ);c.setLineDash([5,4]);c.strokeStyle='#fff';c.beginPath();c.arc(nx,nz,q.nextRadius*s,0,Math.PI*2);c.stroke();c.restore();}
  if(r.route&&r.elapsed<r.route.duration){c.save();c.strokeStyle='#ffedb1';c.lineWidth=2;c.setLineDash([6,6]);c.beginPath();c.moveTo(...point(r.route.fromX,r.route.fromZ));c.lineTo(...point(r.route.toX,r.route.toZ));c.stroke();c.restore();if(!r.practice){const bus=transportAt(r.route,r.elapsed),[x,z]=point(bus.x,bus.z);c.fillStyle='#ffda70';c.fillRect(x-5,z-5,10,10);}}
  if(full){for(const landmark of map.landmarks){const [x,z]=point(landmark.x,landmark.z);c.strokeStyle='#fff2b7';c.lineWidth=1.5;c.strokeRect(x-3,z-3,6,6);c.font='600 9px system-ui';c.textAlign='center';c.fillStyle='#ffefc2';c.fillText(landmark.name,x,z+12);}
   c.font='800 13px system-ui';c.textAlign='center';c.strokeStyle='#23453b';c.lineWidth=3;c.fillStyle='#fff9e5';for(const poi of map.districts){const [x,z]=point(poi.x,poi.z);c.strokeText(poi.name.toUpperCase(),x,z-35*s);c.fillText(poi.name.toUpperCase(),x,z-35*s);}}
  for(const station of r.relays||[]){const [x,z]=point(station.x,station.z);c.fillStyle='#69e9cd';c.fillRect(x-3,z-3,6,6);if(full){c.font='bold 10px system-ui';c.fillText('RELAY',x,z+15);}}
  if(!r.practice)for(const marker of bossMapMarkers(map,state.players,mapVaults(map).map(v=>({...v,opened:vaultOpen(r,v.id)})))){const[x,z]=point(marker.x,marker.z);c.save();c.beginPath();c.arc(x,z,full?22:10,0,Math.PI*2);c.fillStyle='#b3443338';c.fill();c.strokeStyle=marker.color;c.lineWidth=full?3:2;c.stroke();c.fillStyle=marker.color;c.font='bold '+(full?22:15)+'px system-ui';c.textAlign='center';c.strokeStyle='#132f40';c.lineWidth=3;c.strokeText(marker.alive?'★':'◇',x,z+5);c.fillText(marker.alive?'★':'◇',x,z+5);if(full){c.font='bold 10px system-ui';c.fillText(marker.label,x,z+35);}c.restore();}

  const guidance=keycardRoute(map,r,p);if(guidance){const goal=guidance[0],[x,z]=point(goal.x,goal.z);c.save();c.strokeStyle='#9ceaff';c.lineWidth=2;c.setLineDash([4,3]);c.beginPath();c.moveTo(...point(p.x,p.z));c.lineTo(x,z);c.stroke();c.setLineDash([]);c.strokeRect(x-5,z-5,10,10);c.restore();}
  for(const chest of r.chests||[])if(chest.supply&&!chest.opened){const [x,z]=point(chest.x,chest.z);c.fillStyle='#ffd377';c.beginPath();c.moveTo(x,z-5);c.lineTo(x+5,z);c.lineTo(x,z+5);c.lineTo(x-5,z);c.closePath();c.fill();}
  for(const marker of visibleMarkers(state,p)){const [x,z]=point(marker.x,marker.z);const owner=state.players.find(o=>o.id===marker.player),style=owner?teamStyle(state.players,owner):{slot:1,color:'#7dddf4'};c.fillStyle=marker.kind==='danger'?'#ff795f':style.color;c.strokeStyle='#102e36';c.lineWidth=2;c.beginPath();c.moveTo(x,z-7);c.lineTo(x+6,z);c.lineTo(x,z+7);c.lineTo(x-6,z);c.closePath();c.fill();c.stroke();c.fillStyle='#102e36';c.font='bold 10px system-ui';c.textAlign='center';c.fillText(marker.kind==='danger'?'!':String(style.slot),x,z+3);}
  if(this.waypoint){const[x,z]=point(this.waypoint.x,this.waypoint.z);c.fillStyle='#ffdd77';c.strokeStyle='#493e23';c.lineWidth=2;c.beginPath();c.arc(x,z,full?7:5,0,Math.PI*2);c.fill();c.stroke();}
  for(const mate of state.players.filter(o=>!r.practice&&teammates(state.options,p,o)&&o.contestant&&o.health>0)){const [x,z]=point(mate.x,mate.z);const style=teamStyle(state.players,mate);c.fillStyle=style.color;c.strokeStyle='#124641';c.lineWidth=2;c.beginPath();c.arc(x,z,full?7:5,0,Math.PI*2);c.fill();c.stroke();c.font='bold 9px system-ui';c.textAlign='center';c.fillStyle='#152a35';c.fillText(String(style.slot),x,z+3);if(full){c.font='bold 12px system-ui';c.fillStyle=style.color;c.fillText(style.slot+' '+mate.name,x,z-12);}}
  if(p&&!r.practice){const[x,z]=point(p.x,p.z);c.save();c.translate(x,z);c.rotate(-p.yaw);c.fillStyle='#fff';c.strokeStyle='#244c5c';c.lineWidth=2;c.beginPath();c.moveTo(0,-8);c.lineTo(5,6);c.lineTo(0,3);c.lineTo(-5,6);c.closePath();c.fill();c.stroke();c.restore();}
  c.font=`800 ${full?18:12}px system-ui`;c.textAlign='center';c.fillStyle='#fff';c.fillText('N',w/2,full?23:16);
 }
 update(state,local,watched,label,paused){
  const active=!!state?.royale;this.root.hidden=!active;document.body.classList.toggle('in-royale',active);document.body.classList.toggle('in-duos',active&&isTeamRoyale(state.options));document.body.classList.toggle('in-spawn-island',!!state?.royale?.practice);
  if(!active||!local)return;
  this.nodes??=new Map();const $=id=>{let node=this.nodes.get(id);if(!node?.isConnected){node=document.getElementById(id);if(node)this.nodes.set(id,node);}return node;},r=state.royale,p=watched||local;
  let bossBar=$('boss-vitals');if(!bossBar){bossBar=document.createElement('div');bossBar.id='boss-vitals';this.root.append(bossBar);}const boss=state.players.filter(o=>o.boss&&o.health>0&&o.lastDamage>0).sort((a,b)=>dist(p,a)-dist(p,b))[0],bossPos=boss&&this.project?.({...boss,y:boss.y+2.35});bossBar.hidden=!bossPos||bossPos.offscreen||dist(p,boss)>95;if(!bossBar.hidden){bossBar.style.left=bossPos.x+'%';bossBar.style.top=bossPos.y+'%';const bossHTML=`<strong>${escape(boss.name)}</strong><small>${Math.ceil(boss.health)} HEALTH · ${Math.ceil(boss.shield)} SHIELD</small><progress class="shield" max="${boss.maxShield}" value="${boss.shield}"></progress><progress max="${boss.maxHealth}" value="${boss.health}"></progress>`;if(bossBar.innerHTML!==bossHTML)bossBar.innerHTML=bossHTML;}
  let crownBadge=$('crown-status');if(!crownBadge){crownBadge=document.createElement('div');crownBadge.id='crown-status';crownBadge.innerHTML=CROWN_ICON+'<span></span>';this.root.append(crownBadge);}crownBadge.hidden=!local.crown;setText(crownBadge.querySelector('span'),`${local.crownWins||0} CROWN WINS`);
  const invCrown=document.querySelector('.inventory-crown');if(invCrown){invCrown.hidden=!local.crown;setText(invCrown.querySelector('small'),`${local.crownWins||0} crowned victories · Season 1`);}
  this.waypoint=visibleMarkers(state,local).find(m=>m.player===local.id)||null;
  const mates=state.players.filter(o=>teammates(state.options,local,o)&&o.contestant).sort((a,b)=>(a.teamSlot||0)-(b.teamSlot||0));
  const markerHTML=visibleMarkers(state,local).filter(m=>!r.practice||!m.planning).map(m=>{const pos=this.project?.(m);if(!pos)return '';const owner=state.players.find(o=>o.id===m.player),style=owner?teamStyle(state.players,owner):{slot:1,color:'#7dddf4'};return `<div class="duo-world-marker ${m.kind}" style="left:${pos.x}%;top:${pos.y}%;--team-color:${style.color}"><b>${pos.offscreen?'➤':m.kind==='danger'?'!':'◆'}</b><span>${style.slot} · ${escape(m.kind==='danger'?'DANGER':m.label||'MARKER')} · ${Math.round(dist(local,m))} m</span><small>${escape(m.name)}</small></div>`;}).join('')+mates.filter(m=>m.health>0&&!m.spectating).map(m=>{const pos=this.project?.({...m,y:m.y+2.4});if(!pos)return '';const style=teamStyle(state.players,m);return `<div class="duo-world-marker teammate" style="left:${pos.x}%;top:${pos.y}%;--team-color:${style.color}"><b>${pos.offscreen?'➤':m.downed?'＋':style.slot}</b><span>${escape(m.name)} · ${Math.round(dist(local,m))} m</span></div>`;}).join('');if(this.markerHTML!==markerHTML){$('duo-markers').innerHTML=markerHTML;this.markerHTML=markerHTML;}
  this.root.classList.toggle('downed',!!local.downed);document.body.classList.toggle('is-downed',!!local.downed);
  $('downed-status').hidden=!local.downed;setText($('downed-status'),local.downed?`${local.reviverId?'TEAMMATE REVIVING':'DOWNED · CRAWL TO COVER'} · ${Math.ceil(local.health)} VITALITY`:'');
  const mate=mates.filter(m=>m.downed&&m.health>0&&reviveAccessible(getMap(state.options.map),local,m)).sort((a,b)=>dist(local,a)-dist(local,b))[0],duo=$('duo-hud');duo.hidden=!isTeamRoyale(state.options);
  if(!duo.hidden){const markup=mates.length?mates.map(m=>{const style=teamStyle(state.players,m),status=m.connected===false&&!m.bot?'DISCONNECTED':m.downed?'DOWNED':m.health>0?'ACTIVE':'ELIMINATED';return `<div class="team-hud-member" style="--team-color:${style.color}"><strong>${style.slot} · ${escape(m.name)}</strong><small>${status}${m.health>0?' · '+Math.ceil(m.health)+' H / '+Math.ceil(m.shield||0)+' S':''}</small><progress class="shield" value="${m.shield||0}" max="100" aria-label="${escape(m.name)} shield"></progress><progress value="${Math.max(0,m.health)}" max="100" aria-label="${escape(m.name)} health"></progress></div>`;}).join(''):`<small>${state.options.teamSize===4?'SQUADS':'DUOS'} · NO TEAMMATES</small>`;if(duo.innerHTML!==markup)duo.innerHTML=markup;}
  const matchKey=r.matchId+':'+state.round;if(this.flightMatch!==matchKey){this.flightMatch=matchKey;this.flightDismissed=false;}
  setText($('royale-flight-close'),label('dismissFlight')+' Close');
  const closest=getMap(state.options.map).districts.reduce((a,b)=>Math.hypot(b.x-p.x,b.z-p.z)<Math.hypot(a.x-p.x,a.z-p.z)?b:a);
  const heading=(((-p.yaw*180/Math.PI)%360)+360)%360;
  setText($('royale-compass'),`${['N','NE','E','SE','S','SW','W','NW'][Math.round(heading/45)%8]}  ${Math.round(heading)}°  ·  ${Math.hypot(closest.x-p.x,closest.z-p.z)<62?closest.name:'Ravel Coast Wilds'}${this.waypoint?'   ◆ '+Math.round(Math.hypot(p.x-this.waypoint.x,p.z-this.waypoint.z))+' m':''}`);
  setText($('royale-alive'),r.alive);setText($('royale-elims'),local.kills||0);setText($('royale-phase'),r.practice?'SPAWN ISLAND':r.elapsed<35?'DROP ZONE':`STORM ${r.storm.index+1}`);
  setText($('royale-alive'),r.practice?r.contestants:r.alive);
  if(isTeamRoyale(state.options)&&!r.practice)setText($('royale-phase'),`${r.teamsAlive} ${state.options.teamSize===4?'SQUADS':'DUOS'} · STORM ${r.storm.index+1}`);
  if(!this.mapAt||state.time-this.mapAt>.2){const mapKey=[state.options.map,r.matchId,Math.round(p.x*2),Math.round(p.z*2),Math.round(p.yaw*40),r.alive,r.storm?.index,Math.round(r.storm?.radius||0),Math.round(r.storm?.x||0),Math.round(r.storm?.z||0),Math.round(r.elapsed||0),r.buildVersion,visibleMarkers(state,p).map(m=>m.id+':'+m.x+':'+m.z).join('|'),mates.map(m=>m.id+':'+Math.round(m.x)+':'+Math.round(m.z)+':'+(m.health>0)).join('|')].join(';');if(mapKey!==this.mapKey){this.drawMap($('royale-mini'),state,p);this.drawMap($('royale-fullmap'),state,p,true);this.mapKey=mapKey;}this.mapAt=state.time;}
  setText($('shield'),Math.ceil(p.shield||0));$('shield-fill').style.width=Math.max(0,Math.min(100,p.shield||0))+'%';setText($('royale-stamina'),Math.ceil(p.stamina||0));$('royale-stamina-fill').style.width=(p.stamina||0)+'%';
  this.label=label;const key=[...(p.inventory||[]).map(i=>i?i.id+':'+i.rarity+':'+!!i.weapon+':'+!!i.pickaxe:''),...[0,1,2,3,4,5].map(i=>label(inventoryActionForSlot(i)))].join('|');if(key!==this.lastKey){$('royale-hotbar').innerHTML=this.slotMarkup(p);this.lastKey=key;}
  for(const button of $('royale-hotbar').querySelectorAll('[data-royale-slot]')){const index=Number(button.dataset.royaleSlot),item=p.inventory?.[index],selected=index===p.slot;button.classList.toggle('selected',selected);button.setAttribute('aria-pressed',String(selected));const count=button.querySelector('b'),text=item?(item.pickaxe?'∞':item.weapon?String(item.ammo):['jumpRig','shadowstep'].includes(item.id)?(item.charges??(item.id==='shadowstep'?SHADOWSTEP.charges:3))+'/'+(item.id==='shadowstep'?SHADOWSTEP.charges:3):item.id==='anchorWinch'?'∞':item.count+'×'):'';if(count&&count.textContent!==text)count.textContent=text;}
  this.time=state.time;this.updateRigRings($('royale-hotbar'),p);this.updateInventory(local);
  const warmup=r.practice;
  $('royale-flight-close').hidden=warmup;
  const flight=['transport','dive','glide','launch'].includes(local.flight)&&local.health>0;
  $('royale-flight').hidden=(!flight&&!warmup)||(!warmup&&!!this.flightDismissed);$('royale-flight').classList.toggle('airborne',local.flight!=='transport');
  setText($('royale-flight-title'),local.flight==='transport'?`${r.elapsed<3?'Doors open in '+Math.ceil(3-r.elapsed):'Choose your landing spot'}${r.elapsed>=3?' · '+Math.ceil(r.route.duration-r.elapsed)+'s':''}`:local.flight==='dive'?'Freefall':'Glider deployed');
  setText($('royale-flight-help'),local.flight==='transport'?'Look around with your mouse or touch look. Open the map, choose a district, then jump.':local.flight==='dive'?`${label('forward')} to steer · ${label('jump')} to deploy glider`:`${label('jump')} to dive again at altitude. Your glider opens automatically near the ground.`);
  $('royale-flight-button').hidden=['glide','launch'].includes(local.flight);$('royale-flight-button').disabled=local.flight==='transport'&&r.elapsed<3;setText($('royale-flight-button'),local.flight==='transport'?`JUMP · ${label('jump')}`:`DEPLOY GLIDER · ${label('jump')}`);
  if(warmup){setText($('royale-flight-title'),`KESTREL AIRFIELD · ${r.contestants}/${state.options.capacity} contestants`);setText($('royale-flight-help'),`${state.options.session==='offline'?'Offline · ':''}Kestrel departs in ${r.countdownStarted===false?'Waiting for players':Math.max(0,Math.ceil(r.queueEnds-state.time))+'s'} · ${r.humanContestants??state.players.filter(p=>!p.bot&&p.contestant&&!p.spectating).length} real players · ${r.botContestants??state.players.filter(p=>p.bot&&p.contestant).length} bots · Practice equipment resets at departure`);$('royale-flight-button').hidden=true;}
  const outside=r.storm.active&&Math.hypot(p.x-r.storm.x,p.z-r.storm.z)>r.storm.radius;
  setText($('royale-storm-warning'),outside?`IN THE STORM · ${Math.ceil(Math.hypot(p.x-r.storm.x,p.z-r.storm.z)-r.storm.radius)} m TO SAFETY`:r.storm.active?`${r.storm.closing?'STORM CLOSING':'STORM CLOSES IN'} ${Math.ceil(r.storm.seconds)}s`:'');
  $('royale-storm-warning').classList.toggle('danger',outside);this.root.classList.toggle('outside-storm',outside);
  const use=p.use;$('royale-use').hidden=!use&&!p.chestProgress;
  setText($('royale-use-label'),use?`Using ${ITEMS[use.id].name} · ${Math.max(0,use.end-state.time).toFixed(1)}s`:'Searching chest…');
  $('royale-use-fill').style.width=(use?Math.min(1,(state.time-use.start)/(use.end-use.start)):Math.min(1,p.chestProgress/.8))*100+'%';
  const rescue=local.reviving?state.players.find(o=>o.id===local.reviving):local.downed&&local.reviverId?local:null;
  if(rescue){$('royale-use').hidden=false;setText($('royale-use-label'),`${local.downed?'Being revived':'Reviving '+rescue.name} · ${Math.max(0,REVIVE_RULES.seconds-rescue.reviveProgress).toFixed(1)}s`);$('royale-use-fill').style.width=(rescue.reviveProgress/REVIVE_RULES.seconds*100)+'%';}
  let prompt='';if(canFight(local)&&local.flight==='ground'&&!paused){
   const accessible=source=>{const item=source.motion?{...source,y:lootHeight(source,state.time)}:source;if(dist(local,item)>3.2||item.landAt>state.time)return false;const from={x:local.x,y:local.y+.9,z:local.z},dx=item.x-from.x,dy=item.y+.6-from.y,dz=item.z-from.z,len=Math.hypot(dx,dy,dz)||1;return wallDistance(getMap(state.options.map),from,{x:dx/len,y:dy/len,z:dz/len},len)>=len-.15;};
   const chest=nearbyItems(r,'chests',local,3.3).find(c=>!c.opened&&accessible(c));const item=nearbyItems(r,'loot',local,3.2).filter(i=>!(i.droppedBy===local.id&&i.pickupAfter>state.time)&&accessible(i)).sort((a,b)=>dist(local,a)-dist(local,b))[0];
   if(item?.ammoType)prompt=`${escape(item.count)} ${escape(item.ammoType.toUpperCase())} AMMO<small>Automatic pickup</small>`;
   else if(chest)prompt=`<kbd>${escape(label('interact'))}</kbd> HOLD TO SEARCH ${chest.supply?'SUPPLY DROP':chest.epic?'RARE CHEST':'CHEST'}`;
   else if(item){const info=itemInfo(item),swap=pickupNeedsSwap(local,item),rarity=RARITIES[item.rarity??ITEMS[item.id]?.rarity??0];prompt=`<kbd>${escape(label('interact'))}</kbd> ${escape(info.name)} <span style="color:${info.color}">${item.weapon||['jumpRig','shadowstep','anchorWinch','veilProjector','victoryCrown'].includes(item.id)?rarity.name:'×'+item.count}</span><small>${swap?'Press to swap selected slot':'Pick up'}</small>`;}
  }
  const relay=r.relays?.find(o=>dist(local,o)<3);if(relay&&!paused)prompt=`<kbd>${escape(label('interact'))}</kbd> ${relay.cooldown>state.time?'RELAY RECHARGING · '+Math.ceil(relay.cooldown-state.time)+'s':'HOLD 3s TO SCAN · '+Math.round(relay.progress/3*100)+'%'}<small>Reveals nearby activity AND your location for 12 seconds</small>`;
  const field=!paused&&frontierPrompt(getMap(state.options.map),r,local);const cache=!paused&&bossCachePrompt(r.bossCaches,local);if(cache)prompt=`<kbd>${escape(label('interact'))}</kbd> ${escape(cache.text)}${cache.progress?'<small>'+Math.round(cache.progress/1.5*100)+'% AUTHENTICATING</small>':''}`;
  if(field)prompt=`<kbd>${escape(label(field.kind==='ride'?'jump':'interact'))}</kbd> ${escape(field.text)}${field.kind==='vault'&&field.progress?'<small>'+Math.min(100,Math.round(field.progress/2*100))+'% AUTHENTICATING</small>':''}`;
  const heldVault=mapVaults(getMap(state.options.map)).find(v=>!vaultOpen(r,v.id)&&v.key===local.inventory?.[local.slot]?.id);const cacheRoute=r.bossCaches?.find(c=>!c.opened&&c.key===local.inventory?.[local.slot]?.id);const route=cacheRoute?[{...cacheRoute,label:cacheRoute.name.toUpperCase()}]:keycardRoute(getMap(state.options.map),r,local),guide=$('keycard-guide');guide.hidden=!route||paused||local.health<=0;
  if(!guide.hidden){const target=route[0],angle=(Math.atan2(local.x-target.x,local.z-target.z)-local.yaw)*180/Math.PI;guide.innerHTML=`<b><span class="keycard-arrow" style="transform:rotate(${angle}deg)">↑</span>${cacheRoute?escape(cacheRoute.name.toUpperCase()):escape(heldVault?.name?.toUpperCase()||'VAULT')} · ${Math.round(dist(local,target))} m</b><small>${escape(target.label||'DESCEND THE ARCHIVE STAIRS')} · ${Math.round(target.y-local.y)} m elevation</small><small>Follow the blue route · Hold ${escape(label('interact'))} at the reader</small>`;}
  $('royale-stamina').closest('.stamina').classList.toggle('exhausted',!!local.exhausted);
  if(state.options.training){setText($('royale-flight-title'),'FIELD TRAINING · '+Object.values(local.tutorial||{}).filter(Boolean).length+'/6');setText($('royale-flight-help'),['move','fire','slide','build','edit','boost'].map(k=>(local.tutorial?.[k]?'✓ ':'◇ ')+k.toUpperCase()).join(' · ')+' · Inventory: all weapons & supplies. Esc: leave.');}
  if(local.recap&&local.health<=0)prompt=`<strong>ELIMINATED · ${escape(local.recap.weapon)}</strong><small>${local.recap.distance} m · ${local.recap.damage} final-hit damage · ${local.recap.critical?'Critical hit':'Body / environment'}</small>`;
  if(mate?.downed&&local.health>0&&!local.downed&&reviveAccessible(getMap(state.options.map),local,mate))prompt=`<kbd>${escape(label('interact'))}</kbd> HOLD TO REVIVE ${escape(mate.name)}<small>Stay close · Taking damage interrupts</small>`;
  if(this.prompt!==prompt){$('royale-prompt').innerHTML=prompt;this.prompt=prompt;}$('royale-prompt').hidden=!prompt;
 }
}
